packages/build-tools/package.json, packages/build-tools/src/ios/xcpretty.ts, yarn.lock
Split the `expo run:ios` formatter into `@expo/xcpretty` so we can properly format metro build errors and other optimizations.
- https://github.com/expo/expo-cli/pull/3538
- https://github.com/expo/third-party/pull/49
- Fixes https://exponent-internal.slack.com/archives/C02123T524U/p1622334291038200
Locally:
=> Use expo run formatter/logger

packages/build-tools/src/builders/iosManaged.ts, packages/build-tools/src/managed/EjectProvider.ts, packages/build-tools/src/managed/NpxExpoCliEject.ts
https://linear.app/expo/issue/ENG-1191/automatically-populate-apple-team-id-env-var-in-eas-build-jobs
move credentials prepare phase at the begging
pass teamId if available to the rebuild phase
TODO
=> add APPLE_TEAM_ID env to prebuild phase

packages/eas-build-job/src/metadata.ts
Used in https://github.com/expo/eas-cli/pull/454.
Added `boolean` to the union of types in `trackingContext`.
TypeScript should compile without errors.
=> Allow Metadata.trackingContext to include `boolean` fields

packages/build-tools/package.json, packages/local-build-plugin/package.json, yarn.lock
Currently in our [SDK 42 beta blog post](https://blog.expo.io/expo-sdk-42-beta-is-now-available-e505770389e7) I recommend users set `"expoCli": "4.7.1"` for their build profiles, but we can just go ahead and bump it on EAS Build.
Updated dependencies on `@expo/config-plugins` and `expo-cli`
CI
=> [build-tools][local-build-plugin] Bump deps for SDK 42 beta

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
For https://linear.app/expo/issue/ENG-1292/account-for-universal-enterprise-distribution-in-install-modal
Added `iosEnterpriseProvisioning` to build metadata
Unit test
=> [eas-build-job] add iosEnterpriseProvisioning to metadata

packages/eas-build-job/src/index.ts, packages/eas-build-job/src/job.ts, packages/eas-build-job/src/metadata.ts
do not export schemas, if they are used with the wrong version of joi then it can fail in unexpected ways
- remove exports
- add validator function
=> validate metadata using joi bundled with eas-build-job

packages/build-tools/src/context.ts, packages/build-tools/src/utils/appConfig.ts
process.exit called in app config crashes entire build process
- replace process.exit with throw exception when evaluating app.config
- read stdout and stderr during config evaluation and print it in case of errors
tested with `eas build --local` and local build with turtle
=> [build-tools] handle exit calls in app.config.js

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/ios/credentials/manager.ts, packages/build-tools/src/ios/fastlane.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/ios.ts
We (not-that-)recently changed the eas.json format but the API build job object stayed the same.
This PR unifies the eas.json and build job formats. 
Android:
- Deprecate the `DEVELOPMENT_CLIENT` value for `buildType`.
- Add `developmentClient: boolean`.
iOS:
- Drop `buildType`.
- Drop `distribution`.
- Add `developmentClient: boolean`.
- Add `simulator: boolean`.
None
=> unify eas.json and build job format

packages/build-tools/package.json, packages/local-build-plugin/package.json, yarn.lock
Mostly because Evan published the new version of `@expo/xcpretty`:
Upgraded deps
None.
=> upgrade @expo/config-plugins, @expo/xcpretty and expo-cli

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/ios/fastlane.ts, packages/build-tools/src/ios/gymfile.ts, packages/build-tools/templates/Gymfile.archive.template
Fixes https://github.com/expo/eas-cli/issues/693
Check the entitlements file and see if `com.apple.developer.icloud-container-environment` is set. If so, add `iCloudContainerEnvironment` to the `export_options` in Gymfile.
Will test on staging.
=> [build-tools] set iCloudContainerEnvironment in Gymfile when com.apple.developer.icloud-container-environment entitlement is set

packages/build-tools/src/utils/appConfig.ts
`process.cwd` returns wrong value when resolving app config.
Override `process.cwd` so it returns the project dir.
Will test on staging.
=> [build-tools] set correct cwd when reading app config

packages/eas-build-job/src/android.ts
allow users to switch between java versions without any build time impact
remove android SDK version from image name
map react-native version to the build image
=> [eas-build-job] Add separate java images

packages/eas-build-job/src/android.ts, packages/eas-build-job/src/job.ts, packages/eas-build-job/src/metadata.ts
In previous PR I didn't realize that image detection is part of eas-build-job package
will test after publish
=> auto-detect default android image

packages/build-tools/src/builders/android.ts, packages/build-tools/src/context.ts, packages/build-tools/src/index.ts, packages/build-tools/src/ios/fastlane.ts, packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/build.ts, packages/local-build-plugin/src/config.ts, packages/local-build-plugin/src/exit.ts, packages/local-build-plugin/src/ios.ts, packages/local-build-plugin/src/parseInput.ts
Support partial builds that can be used to implement inspect functionality in eas-cli
run build and build:inspect with various options
=> support partial builds

packages/build-tools/src/utils/expoUpdates.ts
Fix this display bug:
the app config may have runtime version *objects* as well as strings, so we should use `getRuntimeVersionNullable` to process it.
=> [build-tools] fix display bug

packages/local-build-plugin/package.json, packages/local-build-plugin/src/buildArtifact.ts, packages/local-build-plugin/src/config.ts, yarn.lock
- support `--output` flag in `eas-cli`
- closes #64 
add env variable that overrides artifact name
change default name (using timestamp instead of formated time is less human-readable but name look cleaner without all those `:`/`-`)
run local build
=> specify custom artifact path via env

packages/build-tools/src/android/gradleConfig.ts, packages/build-tools/src/builders/android.ts, packages/build-tools/templates/eas-build.gradle
We want to get rid of `eas build:configure`. Because of that, we need to inject signing config into `build.gradl` in `@expo/build-tools`.
- Basically copy-paste logic from EAS CLI/`@expo/config-plugins`:
- Remove `eas-build.gradle` from project if it already exists.
- Create a new `eas-build.gradle` from the template.
- Add the `apply ...` line to `build.gradle` if it's not there yet.
- The above logic is only executed if build credentials exist.
Tested locally with https://github.com/expo/eas-cli/pull/888
=> [build-tools] configure build.gradle when building android projects

LICENSE, README.md
* The badge on the README said MIT. Changed it to BSL, the main license here.
* The link in the readme pointed to expo.io instead of expo.dev.
There are no actual license changes, just cosmetics.
=> Update license badge in README and pricing URL in license

packages/eas-build-job/src/android.ts, packages/eas-build-job/src/ios.ts, packages/local-build-plugin/src/eject.ts
To support custom options for the prebuild command
add an experimental field to the job object
use new option when running prebuild command for local builds
prebuildCommand can be in form
- `expo prebuild --template sjdlkhfjlksd`
- `expo-cli prebuild --template sjdlkhfjlksd`
- `prebuild --template sjdlkhfjlksd`
if platform or non interactive is not specified is added to the command
run local build with custom prebuild option
=> add custom prebuild command to job api

packages/local-build-plugin/package.json, yarn.lock
`local-build-plugin` depended on `eas-cli` to have `env-paths` in its dependencies.
Added the dependency to `package.json`
N/A
=> [local-build-plugin] add explicit dependency to env-paths

packages/eas-build-job/src/ios.ts
We want to drop support for macOS Catalina images.
Drop support for macOS Catalina images.
I will test it with turtle-api changes.
=> [eas-build-job] remove support for catalina images

packages/build-tools/src/android/__tests__/expoUpdates.test.ts, packages/build-tools/src/android/expoUpdates.ts
Android makes a best guess cast when interpreting metadata values. This can lead to discordance between the releaseChannel stored by the build and the releaseChannel of a published update. 
The motivating example/bug is when a user had `1.0` as a releaseChannel.
Store the releaseChannel as a string resource to ensure Android interprets it as a string.
1. set releaseChannel to `1.0` in eas.json
2. build locally, install into an emulator.
3. publish to `1.0`
4. confirm app downloads and loads update.
=> [build-tools] store release channel name as a string resource

packages/build-tools/src/android/expoUpdates.ts
when we read and write XML values, string values are escaped twice
unescape values on read
tested with local build and pap that had `'` in name
=> unescape string when reading xml

packages/build-tools/src/utils/prebuild.ts
When refactoring eject provider I missed `--no-install` option
add `--no-install` options
not tested
=> [build-tools] add `--no-install` to prebuild command

packages/build-tools/templates/eas-build.gradle
https://github.com/expo/eas-cli/issues/1040 gradle tools 7.1.2 (does not allow to override keystore after project is evaluated)
https://github.com/expo/eas-cli/issues/1037 gradle tools 7.0.4(does not allow to override keystore after some specific task)
this is potentially breaking change for older version of gradle tools if someone has code that is overriding keystore config as part of a gradle task
Context, why `whenTaskAdded` was used https://github.com/expo/expo-cli/pull/2833/files
run build with `expo init` and `react-native init` projects using gradle tools 7.1.2, 7.0.4, and 4.1.0
=> [build-tools] fix missing signingConfigs error

packages/build-tools/src/android/expoUpdates.ts
This should be removed when config plugins were last updated, technically it's a regression but it affects only people that have a name with multiple layers of escape sequences(probably we do not support that either way)
unescaping was backported to configplugins
tested local build with `'` in app name
=> [build-tools] remove unescaping on xml read

packages/eas-build-job/src/ios.ts
builds with xcode 12.5 are no longer accepted into appstore
=> [eas-build-job] Remove xcode 12.5  from default images

packages/build-tools/src/context.ts, packages/build-tools/src/utils/project.ts, packages/eas-build-job/src/logs.ts
https://linear.app/expo/issue/ENG-4643/improve-error-reporting-for-expo-doctor-phase
We don't fail builds for which the expo doctor phase has warnings. On the website, we don't have a way of showing the user that a build phase has warnings. 
This PR introduces a mechanism so that we can mark that a build phase has warnings. This can be used on the website to use e.g. a different icon of the build phase.
- Introduce `.markBuildPhaseHasWarnings()` method to the build context class.
- Introduce `BuildPhaseResult` enum with new value - `warning`.
- Check if there is `Didn't find any issues with the project` in the `expo doctor` output. Call `markBuildPhaseHasWarnings` if it's missing. It's not the best way to detect this, I'll follow up on this in the `expo-cli` repo as this is currently the …
=> [ENG-4643][build-tools] detect warnings in expo doctor phase

packages/eas-build-job/src/errors.ts
https://github.com/expo/turtle-v2/blob/main/src/services/launcher/src/jobService.ts#L105
launcher duplicates all error messages(worker already prints that), I want to add conditions there, but to avoid checking for bunch of status codes  I want everything thrown in launcher to extend server error
=> [eas-build-job] build timeout should be server error

packages/eas-build-job/src/errors.ts
https://linear.app/expo/issue/ENG-4963/tweak-error-message-when-the-correct-bundler-version-is-unavailable
Updated message with suggestion from the issue
Updated old URLs to the docs
=> [eas-build-job] Improve error message for wrong bundler version

.github/workflows/license.yml
Why
---
We want to keep the license's change date fresh but we also don't want lots of commits updating the license. We'll start with an update 3 months for now.
How
---
Change the cron schedule to:
> “At 00:00 on day-of-month 1 in every 3rd month from January through December.”
Test Plan
---
Wait until 2022-07-01 00:00:00
=> [ci] Run license-updating cronjob every 3 months

packages/build-tools/src/utils/hooks.ts, packages/build-tools/src/utils/project.ts
pnpm and yarn2 do enforce immutable lockfiles by default if CI env is present, it looks like some users relied on that value
https://linear.app/expo/issue/ENG-5009/missing-env-vars-in-install-dependencies-step
- Pass all envs we use in EAS_BUILD on install process
- allow mutable install using command line args
- print args that we are passing to command
tested with yarn2  via local build 
verified pnpm behavior by running with option `--no-frozen-lockfile` and `CI` env set
=> [build-tools] pass all eas envs to the install process

packages/build-tools/package.json, packages/build-tools/src/utils/prebuild.ts, yarn.lock
https://linear.app/expo/issue/ENG-4967/update-to-expo-cli-544-and-disable-sharp-on-ios-xcode-133-image
If the custom value is not specified or specified value is higher than 5.4.4 disable sharp
- for cloud builds default version will be higher than 5.4.4 so we can disable it
- for cloud builds with a custom expo-cli version we know the version based on job field
- for local build with the default version we are bundling that version with local build plugin (so version will be at least 5.4.4)
- custom values in eas.json are ignored when building locally (so version will be at least 5.4.4)
- we are not handling the case where users run local build and specifies path to expo-cli via env
=> [build-tools] disable sharp on expo-cli >= 5.4.4

packages/build-tools/src/context.ts, packages/build-tools/src/utils/detectUserError.ts, packages/build-tools/src/utils/project.ts, packages/eas-build-job/src/errors.ts
Occasionally I have seen reports where the error suggests that there is a problem with corrupted packages in npm caches. One recent issue I was able to reproduce, in that case file returned by verdaccio was correct, but the checksum reported by verdacio API was not.
I'm adding this monitoring to help with monitoring the issues, and as way to provide quick workaround for users that hit those issues 
- detect error based on logs and throw custom error
- add onError callback to runBuildPhase
- report erro to sentry
will test on turtle
=> detect and report corupted packages

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/build-tools/src/utils/hooks.ts
There are few places were we are not failing the build, but user could use some visual warning
=> mark build phases with warnings

packages/build-tools/src/utils/detectUserError.ts, packages/eas-build-job/src/errors.ts
Misconfigured git dependencies might cause hard to debug issues when yarn is triggered twice during install
https://github.com/yarnpkg/yarn/issues/7212#issuecomment-493720324
tested regexp in console on example output
=> detect when multiple yarn installs interfere with each other

packages/build-tools/package.json, packages/build-tools/src/ios/xcpretty.ts, yarn.lock
Often users do not know how to find js errors in xcode logs
after build check for section starting with
```
Welcome to Metro!
Fast - Scalable - Integrated
```
and ending with 
```
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code
```
tested with local build
=> [build-tools] Try detect bundler errors in logs

packages/build-tools/src/context.ts, packages/build-tools/src/ios/credentials/__tests__/keychain.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/manager.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/provisioningProfile.test.ios.ts, packages/build-tools/src/utils/__tests__/hooks.test.ts, packages/build-tools/src/utils/__tests__/project.test.ts, packages/build-tools/src/utils/hooks.ts, packages/build-tools/src/utils/packageManager.ts, packages/build-tools/src/utils/prebuild.ts, packages/build-tools/src/utils/project.ts, packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/expoCli.ts, packages/local-build-plugin/src/ios.ts
https://linear.app/expo/issue/ENG-5837/use-local-cli-for-prebuild-in-sdk-46
> The default prebuild command should be npx expo prebuild when the project uses npm or yarn expo prebuild when the project uses yarn.
>
> This is because we are moving away from using a global Expo CLI installation. In the future, this means we will be able to move away from installing Expo CLI on EAS Build workers entirely — everything needed to prebuild the project will be packaged inside of @expo/cli in the expo package. For now, we should leave expo-cli installed on workers even when building SDK 46+ projects because they may run into an issue with the new CLI and want to opt out by using a custom prebuildCommand or setting EXPO_USE_LOCAL_CLI=0 .
I made one change to the behavior from the description. The …
=> [ENG-5837][build-tools][local-plugin] use local CLI for prebuild in SDK 46+

packages/build-tools/src/utils/__tests__/project.test.ts, packages/build-tools/src/utils/project.ts
`EXPO_USE_LOCAL_CLI` was already announced in https://blog.expo.dev/expo-sdk-46-beta-is-now-available-9dfee4040aa7 + is used in the `expo` package - https://github.com/expo/expo/blob/main/packages/expo/bin/cli.js
=> [build-tools] EXPO_USE_GLOBAL_CLI -> EXPO_USE_LOCAL_CLI

packages/build-tools/src/utils/__tests__/project.test.ts, packages/build-tools/src/utils/prebuild.ts, packages/build-tools/src/utils/project.ts
Local Expo CLI doesn't support `--non-interactive` flag for `prebuild`.
Pass `--non-interactive` flag only for global Expo CLI execution.
Test.
=> [build-tools] don't pass --non-interactive flag to prebuild (local CLI)

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
We want to allow users to attach messages to builds.
Add `message` to build's metadata.
Tests
=> [ENG-5836][eas-build-job] add message to metadata

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
Adds `runFromCI` and `runWithNoWaitFlag` to metadata.
=> [ENG-5893][eas-build-job] add runFromCI and runWithNoWaitFlag to metadata

packages/local-build-plugin/src/build.ts, packages/local-build-plugin/src/main.ts, packages/local-build-plugin/src/parseInput.ts
Part of https://linear.app/expo/issue/ENG-3865/testing-on-eas-build-documentation
An env variable with platform would be really useful for running detox tests.
Set `EAS_BUILD_PLATFORM` and a few other env vars that are set when running builds in cloud.
Tested with https://github.com/expo/eas-cli/pull/1256
=> [ENG-3865][local-build-plugin] set more env variables

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/ios/fastlane.ts, packages/build-tools/src/ios/gymfile.ts, packages/build-tools/src/ios/resolve.ts, packages/build-tools/src/ios/tvos.ts, packages/build-tools/templates/Gymfile.simulator.template
This is the first step in adding EAS support for Apple TV. See https://www.notion.so/expo/EAS-for-Apple-TV-99e62720e71f423ca5ae2c146cf2923e for details.
This does not add support for device builds, only for simulator builds.
Added new module `tvos.ts` for Apple TV specific functions, with one new function to check if a build job is for tvOS and not iOS.
Made modifications to Gymfile simulator template and to `gymfile.ts` and `fastlane.ts` to select the correct simulator destination instead of using the hardcoded iOS simulator, and in `ios.ts` to select the correct build artifacts path.
- Create a new React Native TV project with `react-native init ExpoTVTest --template=react-native-tvos`
- Execute `eas build:configure` to create the EAS JSON file
- Add a `preview` profile to `eas.json` to …
=> Support Apple TV simulator builds

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/context.ts, packages/eas-build-job/src/logs.ts
https://linear.app/expo/issue/ENG-5059/add-skipped-prebuild-phase-to-bare-builds
- Add a prebuild step for bare projects and indicate that it was skipped.
- Add a new build phase result type - SKIPPED - so we can mark it with another icon on the website.
Tested with local plugin.
=> [ENG-5059][build-tools] add skipped prebuild phase for bare projects

packages/eas-build-job/src/__tests__/job.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/ios.ts, packages/eas-build-job/src/job.ts
Detect default android image per SDK, e.g. for SDK 46 we should use an image with ndk 21 already installed otherwise build times are significantly increasing
Added tests
=> [eas-build-job] scope android images per sdk

packages/eas-build-job/src/errors.ts
I removed the word "please" from EAS CLI's output. I am removing them from EAS Build based on this suggestion: https://github.com/expo/eas-cli/pull/1250#pullrequestreview-1064909619
Removed "please" from **errors.ts**
Look at the changes and make sure that the error messages still communicate the same point as before, but now without the word "please".
=> [eas-build] remove "please" from error messages

packages/build-tools/package.json, packages/local-build-plugin/package.json, packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/build.ts, packages/local-build-plugin/src/ios.ts, packages/local-build-plugin/src/types.ts, yarn.lock
We have an old version of config-plugins, so it can't evaluate runtimeVersion if appVersion policy is enabled.
- Update @expo/config-plugins
- Pass metadata to the build context (this is not part of the fix, but without this that working was never printed).
run local builds
=> Fix detecting runtime version when appVersion policy is enabled

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/ios/pod.ts
[ENG-4933](https://linear.app/expo/issue/ENG-4933/investigate-cocoapods-cachemirror)
Uses newly created Cocoapods proxy as a source for pods.
This is an experimental feature so we want to use it for 1/3 of builds on our platform to reduce the impact of a potential outage.
Run build locally using MacStadium network and see how it goes.
=> [build-tools][ENG-4933] use cocoapods proxy

packages/build-tools/src/context.ts, packages/build-tools/src/utils/environmentSecrets.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/common.ts, packages/eas-build-job/src/index.ts, packages/eas-build-job/src/ios.ts
We want to support uploading files to EAS Secrets.
This PR changes the format of environment secrets passed to Turtle. Now they have the `type` field which can be either `string` or `file`. For `file` env secrets, we save the value to an ephemeral file and set the env variable to file path.
- Support the new job format (typed secrets).
- Creating files for `file` secret values.
Tested manually.
=> [ENG-4730] add support for environment secret files

packages/build-tools/src/buildErrors/buildErrorHandlers.ts, packages/build-tools/src/buildErrors/userErrorHandlers.ts
Currently, most errors are marked as UnknowError, this will improve what we see in sentry.
My process was to open group of errors with error codes `UNKNOWN_ERRROR`/`UNKNOWN_FASTLANE_ERROR`/`UNKNOWN_GRADLE_ERROR`  are go through stdout of each error. When I see sth that seemed to show up regularly, I added a new match rule if it made sense.
Some errors/regexps I tested in console if regexps match the logs, but not all. If there are errors here it will be caught in the future iterations, so I was not super careful when writing those rules.
=> [build-tools] add custom error definitions

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb, packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb
https://sentry.io/organizations/expoio/issues/3612014624/events/8b2cb187a8ca454da95b12ef1d906fa0/?project=1837720
Our proxy fails to install `razorpay-pod`. I tested it locally and adding it to the blacklist resolves the issue.
Add `razorpay-pod` to the blacklist
Test locally and on staging
=> [cocoapods-nexus-plugin] blacklist `razorpay-pod`

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb, packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb
TrezorCrypto pod doesn't work with our proxy and I've seen some errors about it in Sentry.
Blacklist TrezorCrypto pod
Tested locally
=> [cocoapods-nexus-plugin] blacklist TrezorCrypto pod

packages/build-tools/src/buildErrors/userErrorHandlers.ts
https://linear.app/expo/issue/ENG-6412/clarify-error-message-for-mismatched-pod-locks
- We already have a workflow tag in sentry, so there is no point in separating errors for managed/bare.
- Suggest using website or --clear-cache options instead of cache key.
=> [build-tools] Update error message for pods incompatibility

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb, packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb
Blacklist MapboxMobileEvents pod
I think that all pods which were the dependencies of https://cocoapods.org/pods/MapboxMaps required an authentication token when downloading the pod which caused the proxy to fail
Hopefully, this PR changes it and we will no longer see the issues about Mapbox on our end
Blacklist MapboxMobileEvents pod
Test locally and on staging
=> [cocapods-nexus-plugin] blacklist MapboxMobileEvents pod

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb, packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb
https://forums.expo.dev/t/eas-build-ios-install-pods-error-undefined-method-search-for-https-cdn-cocoapods-org-string/66771
It seems like our proxy had a bug and wasn't able to handle multiple sources set in `Podfile`
In `Pod::Installer::Analyzer` `sources` method make sure that all the sources are converted to `Pod::Source` class instances vs being just the string URLs (what caused the bug for the user). Reuse code from CocoaPods core repo to auto convert URL to the `Pod::Source` class instance using sources manager. This should handle inline sources as well, specified for a given pod.
Test locally and on staging
=> [cocoapods-nexus-plugin] fix problem with multiple sources setup

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb, packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb
https://sentry.io/organizations/expoio/issues/3612014624/events/12b9e78b9d7b429fa28ac86085eaca7a/?project=1837720
A similar issue we've already seen with some other Mapbox pods.
Blacklist `Mapbox-iOS-SDK` pod
Test locally and on staging
=> [cocoapods-nexus-plugin] blacklist Mapbox-iOS-SDK pod

packages/build-tools/src/buildErrors/buildErrorHandlers.ts
In almost all cases if CocoaPods cache fails due to an issue with Nexus3 internal problems we can see in the logs that it either failed with `Error installing ...` or `No podspec found ...` error.
Creating two separate error handlers for these errors can help us monitor issues with the nexus cache more effectively. Generic errors (mostly containing user errors) should still be available under the generic `COCOAPODS_CACHE_ERROR` error in Sentry.
Add two more error handlers for the CocoaPods cache.
Test on staging
=> [build-tools] improve cocoapods cache error handling

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb, packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb
https://sentry.io/organizations/expoio/issues/3612014624/events/26a839144f6145b58c7bb7e957681bf5/?project=1837720
Seems like yet another Mapbox pod requires a token to download it. It causes the CocoaPods cache to fail.
Blacklist the` MapboxNavigation` pod with all dependencies.
=> [cocoapods-nexus-plugin] blacklist few more Mapbox pods

packages/local-build-plugin/src/checkRuntime.ts
We shouldn't require yarn for all local builds.
- Check yarn version only if it's specified in eas.json.
- Do not throw error if yarn is not installed.
=> [ENG-6599][local-build-plugin] Remove requirement to install yarn

packages/build-tools/src/utils/project.ts
If installing dependencies fails, we don't know what was in package.json.
=> [build-tools] move the install dependencies phase after printing package.json

packages/build-tools/src/context.ts, packages/eas-build-job/src/common.ts, packages/eas-build-job/src/index.ts
We want to measure build phase durations and send them to Datadog.
Measure build phase duration and report it to worker with `reportBuildPhaseStats` (this will be passed from worker).
None
=> [ENG-6777][build-tools] measure build phase durations and report to worker

packages/build-tools/src/buildErrors/userErrorHandlers.ts
Companion to https://github.com/expo/expo/pull/19719
This PR adds the docs page to the error message
=> [ENG-6620][build-tools] add docs page to the missing google services file error

packages/build-tools/src/buildErrors/__tests__/detectError.test.ts, packages/build-tools/src/buildErrors/userErrorHandlers.ts
https://linear.app/expo/issue/ENG-6817/better-error-message-when-pod-install-fails-due-to-deployment-target
Add a new error handler with a higher priority than the previous one which was handling this error incorrectly.
Automated test
=> [ENG-6817][build-tools] add better error message when `pod install` fails due to deployment target

packages/build-tools/src/utils/npmrc.ts, packages/build-tools/src/utils/project.ts
Print log if .npmrc is present in project dir. Print only if `NPM_TOKEN` is not set (so the info is not duplicated).
https://linear.app/expo/issue/ENG-6878/log-npmrc-detection-in-eas-build
=> [ENG-6878][build-tools] print log if .npmrc is present in project dir

packages/build-tools/src/buildErrors/userErrorHandlers.ts
After a recent npm update on EAS Build, some previously working projects started to fail with peer deps errors.
Add instructions on how to fix that.
tested regexp in console
=> [ENG-7014][build-tools] Add instruction how to fix incompatible peer deps

packages/build-tools/src/ios/credentials/__tests__/fixtures.ts, packages/build-tools/src/ios/credentials/distributionCertificate.ts, packages/build-tools/src/ios/credentials/provisioningProfile.ts, packages/build-tools/src/ios/fastlane.ts, packages/build-tools/templates/Fastfile.resign.template
Fixes resigning builds introduced in https://github.com/expo/eas-build/pull/179
- Fix signing identity encoding.
- Set correct provisioning profile path in Fastfile.
- Save Fastfile to `fastlane` directory.
- Use named lane in Fastfile.
Tested locally.
=> [ENG-7058][build-tools] fix resigning builds

packages/build-tools/src/android/__tests__/expoUpdates.test.ts, packages/build-tools/src/android/__tests__/fixtures/AndroidManifestWithChannel.xml, packages/build-tools/src/android/expoUpdates.ts, packages/build-tools/src/ios/__tests__/expoUpdates.test.ts, packages/build-tools/src/ios/expoUpdates.ts, packages/build-tools/src/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/utils/expoUpdates.ts
https://linear.app/expo/issue/ENG-7036/log-warning-in-eas-build-with-eas-update-and-no-channel-configured
- Implement the logic from the description.
- BREAKING CHANGE: don't configure classic updates when `updates.url` (app config) i set.
Tests.
=> [ENG-7036][build-tools] configure EAS Update if updates.url (app config) is set

packages/build-tools/src/context.ts
The condition for updating job and env objects is incorrect, it should be possible only from git builds.
=> [build-tools] Fix condition for modifying context

packages/build-tools/src/common/easBuildInternal.ts
eas-cli needs to be aware in what environment it's executed, so it can communicate with local, staging or production environments
pass EXPO_LOCAL=1 or EXPO_STAGING=1 to eas calls
not tested
=> [build-tools] use correct server depending on the build environment

package.json
After some deps update `yarn watch` and `yarn start` in root directory do not show output.
`--stream` flag will make learna stream output of the commands that are running.
Run yarn start
=> Stream output from `yarn watch` and `yarn start` commands

packages/steps/build.sh
`sed` takes different arguments on linux and macos for `-i` option
provide alternatives for both systems
yarn build
=> [steps] Fix build script on linux

packages/build-tools/package.json, packages/build-tools/src/android/credentials.ts, packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/custom.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/common/easBuildInternal.ts, packages/build-tools/src/ios/credentials/manager.ts, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/common.ts, packages/eas-build-job/src/ios.ts, packages/eas-build-job/src/logs.ts, packages/eas-build-job/src/metadata.ts, packages/steps/examples/simple/config.yml, packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildStep-test.ts
Even though the customizable builds (`@expo/steps` library) are in a very early phase of development, we want to let people use them as soon as possible.
This PR integrates `@expo/build-tools` with `@expo/steps`.
- https://github.com/expo/eas-build/pull/194/commits/5ae64045e4a287865b56922f21c18a6510f26001 adds support for custom build in job object:
- Makes the `secrets` object optional.
- Adds `customBuildConfig` with field `path` that points at the build config file (.yml).
- Allows `CUSTOM` for `mode`.
- Allows `custom` for `buildMode` in metadata.
- https://github.com/expo/eas-build/pull/194/commits/2694dc92a185598b7ed3dbaea26ef680de609b98 integrates `@expo/build-tools` with `@expo/steps`
- Handles optional `secrets` field.
- Conditionally runs the regular build workflow or the custom …
=> [ENG-7565] integrate @expo/build-tools with @expo/steps

packages/build-tools/src/builders/custom.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepEnv.ts, packages/steps/src/BuildWorkflow.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts
Fixes https://linear.app/expo/issue/ENG-7649/make-sure-env-vars-are-propagated-to-build-steps
Custom builds don't use the same env as is used for regular builds.
- Execute steps with the env object passed to the workflow. Default to `process.env`.
- In build-tools, use the same env object as for regular builds.
Tests.
=> [ENG-7649][steps] propagate build env to steps

packages/build-tools/src/buildErrors/userErrorHandlers.ts
https://linear.app/expo/issue/ENG-7267/help-users-find-the-xcode-logs-phase-more-easily
Improve error message
=> [ENG-7267][build-tools] indicate in the error message that "Run fastlane" phase doesn't contain all the logs

packages/local-build-plugin/package.json, yarn.lock
`chalk` switched to ESM in v5
downgrade
run local build
=> [local-build-plugin] downgrade chalk

packages/build-tools/src/builders/custom.ts, packages/steps/bin/set-output, packages/steps/bin/upload-artifact, packages/steps/examples/upload-artifacts/config.yml, packages/steps/examples/upload-artifacts/project/abc, packages/steps/examples/upload-artifacts/project/def, packages/steps/examples/upload-artifacts/project/ghi, packages/steps/package.json, packages/steps/src/BuildArtifacts.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildTemporaryFiles.ts, packages/steps/src/BuildWorkflow.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildTemporaryFiles-test.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts, packages/steps/src/__tests__/BuildWorkflowValidator-test.ts, packages/steps/src/bin/uploadArtifact.ts, packages/steps/src/cli/cli.ts, packages/steps/src/errors/BuildInternalError.ts, packages/steps/src/index.ts, yarn.lock
We want to be able to upload artifacts from custom builds.
- Introduce `upload-artifact [--type application-archive|build-artifact]` binary that could be run from any build step.
- The binary copies the artifact to a temporary directory.
- `@expo/build-tools` is responsible for the actual artifacts upload. Because of that, the artifacts are not uploaded at the time the `upload-artifact` command is run but as the last, additional build step. Why? This was the easiest thing I could implement. `@expo/steps` shouldn't have the file upload implementation. Instead, it should be possible to inject some JS code that knows how to upload files. Unfortunately, the `upload-artifact` is run as a separate process so it can have the JS context provided in runtime. The artifact upload feature is going to …
=> [ENG-7648][steps] add support for uploading artifacts

packages/steps/README.md, packages/steps/examples/functions/config.yml, packages/steps/package.json, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildFunction.ts, packages/steps/src/BuildPlatform.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/BuildStepOutput.ts, packages/steps/src/BuildWorkflow.ts, packages/steps/src/__tests__/BuildConfig-test.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/__tests__/BuildStepOutput-test.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts, packages/steps/src/__tests__/BuildWorkflowValidator-test.ts, packages/steps/src/__tests__/fixtures/functions.yml
https://www.notion.so/expo/Customizable-builds-ba301def39b94e0ca7a2d813ba7ec36a?pvs=4
For custom builds, we want to enable users to define functions - special named steps that can be run multiple times from a workflow.
This can be used to share logic between different workflows, and in the future, we'll use them to reimplement all build phases from `@expo/build-tools`.
- _[unrelated to the feature]_ https://github.com/expo/eas-build/pull/199/commits/539678143c26cec6128773955290bb35e6025324 changes the `watch` command to ignore changes in test files. The test files were not recompiled anyway.
- https://github.com/expo/eas-build/pull/199/commits/a026d151f02c6a2f86de11fba9ba94567fb0b0fe makes the `BuildWorkflow.collectArtifactsAsync` function return an empty object if no artifacts were …
=> [ENG-7684][steps] implement reusable functions

packages/steps/bin/upload-artifact, packages/steps/package.json, packages/steps/src/__tests__/BuildWorkflow-test.ts, yarn.lock
When working on the steps library, I noticed that the "returns build artifacts" test from BuildWorkflow-test.ts fails intermittently. I debugged the problem and the problem was I had `yarn watch` and `yarn test:watch` running at the same time. The `upload-artifact` script runs `dist_commonjs/bin/uploadArtifact.cjs` which state is not deterministic because of the `yarn watch` script.
Conditionally use `ts-node` for running `src/bin/uploadArtifact.ts`.
I removed `dist_commonjs` and ran tests, they work fine.
=> [steps] use ts-node in upload-artifact script when running tests

packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildFunction.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/BuildStepOutput.ts, packages/steps/src/BuildWorkflowValidator.ts, packages/steps/src/__tests__/BuildConfig-test.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/__tests__/BuildStepOutput-test.ts, packages/steps/src/__tests__/fixtures/external-functions.yml, packages/steps/src/__tests__/utils/uuid.ts, packages/steps/src/utils/expodash/__tests__/duplicates-test.ts, packages/steps/src/utils/expodash/duplicates.ts
Currently, steps and functions use only bash scripts. For implementing functions that share the JS context with the runner, we need to be able to run any arbitrary JS code. This'll let us implement features like artifact upload without hacks. The artifact upload logic (uploading to a particular storage like S3/GCS) shouldn't be part of the library. Instead, it should be injected when creating the workflow object. With the current approach, where there's a bash command upload-artifact  that can be run from the user's script, we can't really share the upload implementation with that script.
- https://github.com/expo/eas-build/pull/201/commits/272edc85a8b0ab9c6a19637691c872a8bcec6ce7 removes the build context object from the `BuildFunction` constructor. `BuildFunction`s are going to be used …
=> [ENG-7739][steps] add support for running js code in functions

DEVELOPMENT.md, scripts/publish.js
Streamlines eas-cli / eas-build releases.
Currently, the publish script conditionally publishes the local build plugin to the next tag. Instead, we can publish it to latest and tag it with `eas-cli` when we want to update it in EAS CLI.
Companion PR to https://github.com/expo/eas-cli/pull/1759
- Don't tag the local build plugin with `next`. Use `latest` instead.
- Update docs.
- I tagged 0.0.128 with `eas-cli`
None.
=> [ENG-7981] publish eas-cli-local-build-plugin to the latest tag / use the eas-cli tag for EAS CLI

.github/workflows/release.yml
Last PR for https://linear.app/expo/issue/ENG-7981/automate-publishes-in-eas-build
It adds dispatching the `update-eas-build-modules.yml` workflow after successful npm publish.
I'll test it after merging to main.
=> [ENG-7981] open a PR in turtle-v2 with version bumps after npm publish

packages/build-tools/src/common/easBuildInternal.ts, packages/build-tools/src/common/setup.ts
`expo doctor` often times out, new implementation should be lighter and resolve that issue
- Use npx to run expo-doctor (even if user is using different package manager)
- Unrelated to the main purpose of this PR, but I also notice that github commands did not check which version of npm was used, so on npm < 7 it would fail because `--yes` parameter was not yet supported at that time.
Run eas build local and build on local turtle server
=> [build-tools] Use `npx expo-doctor` instead of `expo doctor`

packages/build-tools/src/android/gradle.ts, packages/build-tools/src/common/setup.ts, packages/build-tools/src/utils/processes.ts
Fixes for doctor command
- When process is timing out current implementation does not kill it properly, most likely it's sth npx is doing. Even SIGKILL does not work, it only kills npx process, but actual code keeps running. Given that I'm looking for all children of a process recursively and killing them all.
- New doctor does not support sdks <46, so I'm falling back to the old doctor
- Number of timeouts increased very significantly, plus we are using npx now, so there is additional overhead of running a doctor command, so I'm increasing timeout from 20 seconds to 30.
Tested with local builds for both new sdks and old ones (with timeout small enough to trigger and when command had time to finish)
Did not test on macOS
=> [build-tools] Fix timeout on doctor command

packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/steps/examples/functions/config.yml, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/BuildStepOutput.ts, packages/steps/src/BuildWorkflowValidator.ts, packages/steps/src/__tests__/BuildConfig-test.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/__tests__/BuildWorkflowValidator-test.ts, packages/steps/src/__tests__/fixtures/functions.yml, packages/steps/src/cli/cli.ts
Adds support for "default_value" and "allowed_values" in reusable function inputs.
Example:
```
say_hi:
name: Say Hi!
inputs:
- name: name
default_value: Brent
- name: greeting
default_value: Hi
allowed_values: [Hi, Hello]
command: echo "${ inputs.greeting }, ${ inputs.name }!"
```
- `name` defaults to "Brent".
- `greeting` defaults to "Hi".
- `greeting` can be either "Hi" or "Hello".
- Tests. 
- Tested manually with https://github.com/expo/eas-custom-builds-example/pull/2
- Updated the `functions` example.
=> [ENG-7819][ENG-7738][steps] add support for default and allowed function input values

packages/build-tools/src/utils/processes.ts
When e.g. npm registry is down `npx expo-doctor` will hang before spawning any child processes, so the doctor command will hang for 5 minutes. I noticed that only because the npm cache on staging was broken.
Catch any pgrep errors, so in case of any issues, at least parent process receives a kill signal.
Set npm registry to fake address and run local builds.
=> [build-tools] ignore pgrep errors

packages/eas-build-job/src/common.ts
In https://github.com/expo/eas-build/pull/213 I haven't deleted the default for `cacheDefaultPaths`
Don't apply default in Joi schema
Tests
=> [eas-build-job] allow for undefined `cacheDefaultPaths` in Joi schema

packages/build-tools/src/ios/credentials/__tests__/manager.test.ios.ts, packages/eas-build-job/src/common.ts
Deprecated the old `customPaths` fields and added an analogous `paths` field to `Cache` definition and schema
As per [ENG-8120](https://linear.app/expo/issue/ENG-8120/rename-cachecustompaths-to-cachepaths-in-easjson-and-job-schema) after disabling the default caching paths it doesn't make much sense to have a `customPaths` field so it was decided to simply use `paths` instead
Added a new field `paths` with the same definition as `customPaths`, while keeping the old field but marking it as deprecated for backwards compatibility.
Tests will be conducted within the scope of `eas-cli` and `turtle-v2` once updated `eas-build` is utilised.
=> [eas-build] [ENG-8120] Add `paths` to `Cache` definition

packages/eas-build-job/src/common.ts
Removed the default value from schema definition so that `sanitizeJob` doesn't set the value for the field after it is removed
For `sanitizeJob` not to set the value for the `customPaths` field after it is removed
See: https://linear.app/expo/issue/ENG-8120/rename-cachecustompaths-to-cachepaths-in-easjson-and-job-schema
Removed the default value from `CacheSchema` definition
-
=> [eas-build-job] [ENG-8120] Remove default from `cache.customPaths`

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
We want to display the custom build workflow name on the website.
Add `customWorkflowName` to metadata.
It's gonna be set to the value of https://github.com/expo/eas-build/blob/main/packages/steps/examples/simple/config.yml#L2
Updated test.
=> [ENG-7650][eas-build-job] add custom workflow name to build metadata

.github/workflows/coverage.yml, .github/workflows/test.yml, codecov.yml, package.json, packages/build-tools/jest.config.js, packages/downloader/jest.config.js, packages/eas-build-job/jest.config.js, packages/logger/jest.config.js, packages/steps/jest.config.cjs, packages/steps/package.json, packages/template-file/jest.config.js, packages/turtle-spawn/jest.config.js
https://linear.app/expo/issue/ENG-8519/set-up-test-coverage-bot-for-exposteps
Add changes which set up `codecov` fo this repo based on `eas-cli` setup
Run `test` gh action
=> [ENG-8519] set up test coverage bot for @expo/steps

packages/build-tools/src/buildErrors/userErrorHandlers.ts
After we disabled caching Info.plist file this error message might be a bit confusing.
=> [build-tools] change error message for incompatible pods

packages/build-tools/src/index.ts
In order for the worker to be able to upload XCode logs before it is terminated by the launcher in the case of the build being canceled by the user it needs to import the function to upload the logs from the `build-tools`
Importing the function in `worker`
See: https://linear.app/expo/issue/ENG-8120/rename-cachecustompaths-to-cachepaths-in-easjson-and-job-schema
Added the function to the exports in `index.ts`
No tests
Merging order:
1. This PR ➡️ main
2. https://github.com/expo/turtle-v2/pull/1305 ➡️  main
3. <www_pr> ➡️  main
4. https://github.com/expo/turtle-v2/pull/1306 ⬇️ 
5. https://github.com/expo/turtle-v2/pull/1301 ⬇️ 
6. https://github.com/expo/turtle-v2/pull/1299  ⬇️ 
7. https://github.com/expo/turtle-v2/pull/1298 ➡️  main
Deploying order:
1. This PR (build-tools)
2. Migration …
=> [build-tools] Export function to upload XCode logs

packages/build-tools/src/common/installDependencies.ts, packages/build-tools/src/common/prebuild.ts, packages/build-tools/src/common/setup.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/installNodeModules.ts, packages/build-tools/src/steps/functions/setUpNpmrc.ts, packages/build-tools/src/utils/npmrc.ts
- Extract creating `.npmrc` (when `NPM_TOKEN` is set) as `eas/use_npm_token`.
- Add `eas/install_node_modules`.
Tested with https://github.com/expo/eas-custom-builds-example
=> [ENG-8721[build-tools] custom builds: add `eas/use_npm_token` and `eas/install_node_modules`

packages/build-tools/src/builders/custom.ts, packages/build-tools/src/steps/functions/checkout.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/BuildTemporaryFiles.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts, packages/steps/src/__tests__/utils/context.ts, packages/steps/src/cli/cli.ts
When working on system tests for custom builds, I realized we don't support building custom builds in a non-root project directory (e.g. when you have a monorepo). This PR fixes the issue.
- Introduced `projectTargetDirectory` to `BuildStepContext` so now there are three paths:
- `projectSourceDirectory` - temporary path where the project archive is initially unarchived
- `projectTargetDir` - project root or monorepo/repo root
- `workingDirectory` -  the so-called "react native directory"
- Renamed `baseWorkingDirectory` to `stepsInternalBuildDirectory` to make it more descriptive.
- Updated tests.
- Manually tested all examples from `packages/steps/examples`.
- I added a project with custom builds to https://github.com/expo/turtle-v2-example and was able to build the project.
=> [build-tools][steps] fix building custom builds in non root dir

packages/build-tools/src/common/setup.ts
On the recent github sync @FiberJW pointed out that it's easy to configure a project where projectId in app config is different than real project id.
The same issue exists for non github build if user have some env variables set only locally but not on the EAS Build worker.
I'm open to suggestions, I see 2 alternatives:
- (currently implemented in this PR) Mark the build phase as a warning and log an error, but do not abort the build process
- Throw an error when this happens.
There are also few other open questions:
- do we want to explain potential scenarios why this might happen or just that there is a mismatch?
- do we want to validate any other fileds like that e.g. slug/owner.
- do we want to limit this validation to managed projects only?
tested with local builds by setting …
=> [build-tools] add project id validation

packages/build-tools/src/__mocks__/@expo/logger.ts, packages/local-build-plugin/package.json, packages/local-build-plugin/src/logger.ts, packages/logger/README.md, packages/logger/package.json, packages/logger/src/index.ts, packages/logger/src/pipe.ts, packages/steps/package.json, yarn.lock
Use maintained dependencies.
Inspected differences between `@expo/bunyan` and `bunyan`. There are two:
- `@expo/bunyan` adds unique `id` to every log ([commit](https://github.com/trentm/node-bunyan/commit/e061d981f14d19376d99bd4e4bd7404dab553132)). Do we know if we depend on `id` being present anywhere, or why was it added? I tried to find any usage in `universe`, but didn't find any.
- [removes](https://github.com/trentm/node-bunyan/commit/d8a22b369a98fb70a2ed5b48b4548216e4e62bd8)/[disables](https://github.com/trentm/node-bunyan/commit/428e78233d2049f780c2475a51c392b67704f08c) dtrace — if I understand correctly, Dominik hinted in the issue description that it could have been removed because `expo-cli` depended on `@expo/bunyan`. My wishful guess is that this is no longer an issue, but …
=> Replace `@expo/bunyan` with `bunyan`

packages/logger/package.json
Ought to fix https://github.com/expo/eas-cli/actions/runs/5244436582/jobs/9470444952.
There are two ways to approach this error:
1. move `@types/bunyan` from `devDependencies` to `dependencies` so that `@expo/logger` exposes types for what it exports,
2. require each consumer of the `@expo/logger` package to install `@types/bunyan` on its own.
I think the former approach is better because:
- we "own" the `bunyan` instance we're exporting so we "know" what are its types
- mismatch between what the consumer installs and what we export is less likely.
I'll see if the upgrade in `expo-cli` works nicely.
Not planning to deploy `turtle-v2` after upgrade (it's just types).
=> [logger] Move `@types/bunyan` to dependencies

packages/build-tools/src/common/prebuild.ts
In https://github.com/expo/eas-build/commit/3e1995f112b52ed9adf1df944212f53909b36f56 logic to resolve workingdir was moved to outside function, but the correct directorry was only resolved when doing initial install, but not when runinng install after prebuild
https://github.com/expo/eas-cli/issues/1879
resolve workspace root when running install before prebuild
=> [build-tools] Fix installing node_modules in workspaces

packages/build-tools/src/builders/custom.ts, packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/functions/eas/checkout.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildFunction.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/BuildStepOutput.ts, packages/steps/src/BuildTemporaryFiles.ts, packages/steps/src/BuildWorkflow.ts, packages/steps/src/BuildWorkflowValidator.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/__tests__/BuildStepOutput-test.ts, packages/steps/src/__tests__/BuildTemporaryFiles-test.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts, packages/steps/src/__tests__/BuildWorkflowValidator-test.ts, packages/steps/src/__tests__/utils/context.ts, packages/steps/src/cli/cli.ts, packages/steps/src/index.ts
Refactor context in steps library to make it easier to inject logic from build-tools.
- Separate BuildStepContext into 2 separate types (BuildStepContext - per step context, BuildGlobalContext- context global for entire build)
- Move most BuildStepContext constructor arguments into BuildContextProvider
- Stop using buildId in steps library. As far as I can see that value was only used as random id, so replacing it with just uuidv4() should be fine.
- Provide a way to override env variables in the middle of the build.
- tests
- cli.sh with some of examples
- run local turtle and running custom build from turtle-v2-example
=> [steps] refactor context to simplify injecting logic into stpes library

packages/build-tools/src/builders/custom.ts, packages/steps/bin/set-env, packages/steps/examples/inputs-and-outputs/config.yml, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/BuildTemporaryFiles.ts, packages/steps/src/BuildWorkflow.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts
Add support for overriding envs during the build.
Add set-env executable that will write envs to internal steps directory, similar to how outputs work.
At the end of the build step, all the values are read from directory and added to global context as envs.
test + run local turtle
=> [steps] support overriding env variables

packages/build-tools/src/builders/custom.ts, packages/build-tools/src/common/prebuild.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/eas/installNodeModules.ts, packages/build-tools/src/steps/functions/eas/prebuild.ts, packages/build-tools/src/steps/functions/eas/setUpNpmrc.ts, packages/build-tools/src/steps/functions/utils/uploadArtifact.ts
Move some steps to use new conext
- setup .npmc (just copy paste)
- install dependencies (mostlly copy paste + resolve package manager early and extract install function so it can be used in prebuild)
- prebuild 
- drop support for global cli
- extract the case of customPrebuild command to separate function so it can be removed easily in the future.
- fix type of skipDependencyUpdate arg
- Tried to avoid touching code related to non custom builds
- removed options skipDependencyUpdate and clean (it should not be used in regular builds and custom ones have separate implementation now)
Run some examples, but I didn't test them to carefully. (A lot of changes is landing right now, so it might be better to prioritize speed, so we do not block each other and test it e2e when publishing …
=> [bulid-tools] move some functions to stop using old context

packages/build-tools/src/steps/functions/eas/installNodeModules.ts, packages/build-tools/src/steps/functions/eas/prebuild.ts, packages/build-tools/src/steps/functions/eas/setUpNpmrc.ts, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildFunction.ts, packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildConfig-test.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/fixtures/build-with-import.yml, packages/steps/src/__tests__/fixtures/build.yml, packages/steps/src/__tests__/fixtures/functions.yml, packages/steps/src/index.ts
https://linear.app/expo/issue/ENG-9019/add-support-for-envs-in-step-config
Add support for step envs
This step
```yaml
- run:
id: id123
command: echo "$FOO $BAR"
env:
FOO: bar
BAR: baz
```
will print `bar baz`
You can also pass envs to function calls
```yaml
- say_hi:
env:
ENV1: value1
ENV2: value2
inputs:
name: Dominik
```
=> [ENG-9019][steps] add support for step envs

packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/eas/findAndUploadBuildArtifacts.ts
move next step to stop using old context
- introduce runtime api for communication between worker and custom build
- upload files concurrentlly
Run build on local www (only tested uploading application archive)
=> [build-tools] migrate find and upload artifacts step

packages/steps/package.json, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/BuildWorkflowValidator.ts, packages/steps/src/__tests__/BuildConfig-test.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/__tests__/BuildWorkflowValidator-test.ts, packages/steps/src/__tests__/fixtures/functions-file-1.yml, packages/steps/src/__tests__/fixtures/functions-with-platforms-property.yml, packages/steps/src/__tests__/fixtures/functions.yml, packages/steps/src/__tests__/fixtures/inputs.yml, packages/steps/src/__tests__/fixtures/invalid-functions.yml, packages/steps/src/__tests__/utils/context.ts, packages/steps/src/utils/__tests__/template-test.ts, packages/steps/src/utils/template.ts, yarn.lock
Add support for `json` input type and inputs.
Add support for interpolating global context into inputs and commands.
Allow for `json` inputs and interpolating global context values.
```yaml
build:
name: Functions
steps:
- say_hi:
env:
ENV1: value1
ENV2: value2
inputs:
name: Dominik
build_number: ${ eas.job.version.buildNumber }
json_input:
property1: value1
property2:
- aaa
- bbb
functions:
say_hi:
name: Hi!
inputs:
- name
- name: build_number
type: number
- name: json_input
type: json
default_value:
property1: value1
property2:
- value2
- value3:
property3: value4
```
Interpolated context input values are parsed to a correct type specified in the `type` property
Added automated tests
=> [ENG-9032][ENG-9031][steps] allow JSON inputs and context interpolation

packages/build-tools/src/index.ts
Hooks and runHookIfPresent need to be used by the worker, and they need to be exported
See: https://linear.app/expo/issue/ENG-8506/attempt-to-upload-xcode-logs-when-build-fails-for-unexpected-reason-or
I forgot to export them in the previous PR
Added exports to index.ts
No tests
=> [build-tools] [ENG-8506] Export properties

public/resource-specs/current.json
We should have one source of truth when defining available hardware resources.
Added public file with JSON specification of available machines.
1. https://github.com/expo/eas-build/pull/250
2. https://github.com/expo/expo/pull/22601
3. https://github.com/expo/universe/pull/12701
=> [ENG-8521][eas-build] Add hardware resource specification

packages/steps/package.json, packages/steps/src/BuildConfigParser.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/utils/customFunction.ts, yarn.lock
Follow up to https://github.com/expo/eas-build/pull/252
We want to install dependencies and compile custom JS/TS function modules before running them
If build functions with a path to a custom function module exists add a new step to the build config which runs `packageManager install` and `packageManager run build` for every such function.
Build with custom functions:
Build without custom functions:
Add automated tests
=> [ENG-9010][steps] create step to install dependencies and compile custom function modules

packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/eas/configureExpoUpdatesIfInstalled.ts, packages/build-tools/src/steps/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/steps/utils/android/__tests__/expoUpdates.test.ts, packages/build-tools/src/steps/utils/android/__tests__/fixtures/AndroidManifestWithChannel.xml, packages/build-tools/src/steps/utils/android/__tests__/fixtures/AndroidManifestWithRuntimeVersion.xml, packages/build-tools/src/steps/utils/android/__tests__/fixtures/NoMetadataAndroidManifest.xml, packages/build-tools/src/steps/utils/android/expoUpdates.ts, packages/build-tools/src/steps/utils/expoUpdates.ts, packages/build-tools/src/steps/utils/ios/__tests__/expoUpdates.test.ts, packages/build-tools/src/steps/utils/ios/expoUpdates.ts
https://linear.app/expo/issue/ENG-9477/implement-easconfigure-expo-updates-if-installed
The next step towards making custom builds public
Reimplement [currently existing logic](https://github.com/expo/eas-build/blob/34a9ba17497281793d3fa1f31808911b666dadb6/packages/build-tools/src/utils/expoUpdates.ts#L140-L187) to configure EAS update during the build process
Drop support for classic updates in the new implementation
Add tests
=> [ENG-9477][build-tools] implement `eas/configure-eas-update-if-installed` function

packages/build-tools/src/builders/custom.ts, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts, packages/steps/src/__tests__/utils/context.ts, packages/steps/src/cli/cli.ts
The relative function path was resolved always based on a dirname of the main config path, not based on dirname of the imported config file which actually contains the function declaration.
Resolve relative function path based on the path to the config file which actually contains the function
Tests
=> [steps] fix resolving custom function path

packages/steps/src/scripts/__tests__/runCustomFunction-test.ts, packages/steps/src/utils/customFunction.ts
When we do `eas/checkout` we move project files from `projectSourceDirectory` to `projectTargetDirectory`, but the custom functions paths are resolved before it happens, so if somebody used `eas/checkout` their function path was invalid.
Detect if `eas/checkout` happened, and if so use the correct dir.
Tests
Tested manually as well
=> [steps] improve custom function error message and fix bug with invalid function path after using `eas/checkout` command

packages/local-build-plugin/package.json, yarn.lock
https://github.com/expo/eas-build/commit/273a1504213af8d29f28f7a05ccf97a6597c0f3f#r123488583
Downgrade chalk to `4.1.2` again
Tests
=> [local-build-plugin] downgrade `chalk` to `4.1.2`

packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/utils/runGradle.ts, packages/build-tools/src/steps/utils/android/gradle.ts
Add `utils/run_gradle` function
Add the `utils/run_gradle` function. Copy existing logic and make it independent from the old `BuildContext`.
Test on staging
=> [build-tools] add `utils/run_gradle` function

packages/local-build-plugin/src/workingdir.ts
Fix the issue by creating a `temporary-custom-build` directory when starting the local build
=> [local-build-plugin] create `temporary-custom-build` directory when starting local build

packages/local-build-plugin/src/build.ts
Custom builds don't always need to generate artifacts
Don't throw when no artifacts are present
=> [local-build-plugin] don't throw when artifacts not present at the end of the build

packages/eas-build-job/src/errors.ts
Add unknown custom build error, to distinguish between unknown custom build errors and just unknown build errors in Sentry
Add unknown custom build error
=> [eas-build-job] add unknown custom build error

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
Add the `developmentClient` field to the metadata. Companion to https://github.com/expo/universe/pull/13215
Add the `developmentClient` field to the metadata. Alter Joi schema to validate it.
Add tests
=> [eas-build-job] add `developmentClient` field to metadata

packages/eas-build-job/src/errors.ts, packages/eas-build-job/src/logs.ts
https://linear.app/expo/issue/ENG-9955/link-to-build-logs-from-eas-cli-when-build-fails-for-unknown-reason
Add information about the build phase to the `ExternalBuildError` interface. Add mappings from build phase enum to build phase display names and ids so they can be shared between multiple repos using `eas-build-job` package
Tests
=> [ENG-9955][eas-build-job] add build phase to external build error

packages/build-tools/src/buildErrors/detectError.ts
Use the build phase in the unknown error constructor modified in https://github.com/expo/eas-build/pull/274.
Use the build phase in the unknown error constructor
Tests
=> [build-tools] start using build phase in unknown error constructor

packages/build-tools/src/index.ts
BuildContext contains `packageManager` field, but it can't be used outsidee of build-tools context without this export.
It will be used to fix https://exponent-internal.slack.com/archives/C02123T524U/p1693517365601279
Explicitly export PackageManager in 'index.ts`
=> Export PackageManager enum

.github/workflows/license.yml
https://github.com/expo/eas-build/actions/runs/5428081654/job/14701165896
This workflow broke because of the new branch protection rules we introduced for this repo. 
Use Expo Bot PAT to authorize the update commit. Make an exception in the branch protection rules for Expo Bot (the same way as Dominik did for the `eas-cli` repo some time ago).
Run workflow.
=> [ci] fix licence update workflow

DEVELOPMENT.md, packages/build-tools/package.json, packages/build-tools/src/steps/functions/prebuild.ts, packages/build-tools/src/utils/__tests__/project.test.ts, packages/build-tools/src/utils/packageManager.ts, packages/build-tools/src/utils/project.ts, packages/create-eas-build-function/package.json, yarn.lock
Bun is fast, and people want to use it! https://bun.sh/
Updated `@expo/package-manager` to `1.1.1` which includes bun support, and use `bun` for spawning expo via bun if it is set as the selected package manager.
1. 👉 `@expo/build-tools`: https://github.com/expo/eas-build/pull/279
2. `scheduler`: https://github.com/expo/turtle-v2/pull/1424
3.  `@expo/eas-json` & `eas-cli` https://github.com/expo/eas-cli/pull/2055
4. `www` https://github.com/expo/universe/pull/13473
=> [build-tools] [ENG-10068]: support bun as preferred package managee for build tools

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
We want to know what the user's package manager is going to be at the "install custom tools" step of the build process, so we're determining it based on the user's lockfiles and adding it to build metadata.
1. 👉  `eas-build-job` https://github.com/expo/eas-build/pull/281
2. `www` https://github.com/expo/universe/pull/13522
3. `eas-cli` https://github.com/expo/eas-cli/pull/2067
Added the field.
Unit tests and building locally.
=> [eas-build-job] [ENG-10225] add requiredPackageManager to build metadata

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
https://linear.app/expo/issue/ENG-9957/fix-internal-distribution-pages-for-simulator-builds
Discussion: https://github.com/expo/universe/pull/13523#discussion_r1340072623
Companion to
- https://github.com/expo/universe/pull/13523
- https://github.com/expo/universe/pull/13524
Adds optional simulator flag to metadata to use that instead of overwriting the distribution and losing information if the build is local or not
Updated metadata test
=> [eas-build-job] [ENG-9957] Add simulator flag to metadata

packages/local-build-plugin/src/build.ts
Counterpart to https://github.com/expo/turtle-v2/pull/1448.
Add `NVM_NODEJS_ORG_MIRROR` which we'll soon use in the real Turtle.
None.
=> Add `NVM_NODEJS_ORG_MIRROR` which will be part of `turtle-v2`

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
To accomplish https://linear.app/expo/issue/ENG-10566/create-a-banner-that-links-people-to-changelog-on-build-details-pages www needs to know which image was selected by the user to run the build on.
Companion to https://github.com/expo/eas-cli/pull/2113
Add the `selectedImage` field to the build's metadata, so we know what value the user put in their `eas.json->build->profile->platform->image`.
=> [ENG-10566][eas-build-job] add `selectedImage` to build metadata

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
To accomplish https://linear.app/expo/issue/ENG-10566/create-a-banner-that-links-people-to-changelog-on-build-details-pages www needs to know if custom node version was selected by the user to run the build on.
Add the customNodeVersion field to the build's metadata, so we know what value the user put in their eas.json->build->profile->node.
=> [ENG-10566][eas-build-job] add `customNodeVersion` to build metadata

packages/build-tools/src/ios/credentials/manager.ts
https://linear.app/expo/issue/ENG-10602/tiny-wording-consistency-nit-in-the-prepare-credentials-step
Make logs more consistent.
=> [ENG-10602][build-tools] make logs more consistent in `prepare credentials` phase

packages/build-tools/src/common/installDependencies.ts, packages/build-tools/src/steps/functions/installNodeModules.ts
`--inline-builds` is an interesting option that may help users and us debug Yarn Install errors. ([source](https://github.com/yarnpkg/berry/issues/3764#issuecomment-974519373), [related](https://exponent-internal.slack.com/archives/C031ZK9UWAC/p1698663231179249?thread_ts=1698430427.434299&cid=C031ZK9UWAC))
The option [first](https://github.com/yarnpkg/berry/pull/160) appeared in Yarn v2.
Added `--inline-builds` to `yarn install` options.
Ran `yarn install --inline-builds` in an example project of mine on Yarn 4 and Node 18.
=> Add `--inline-builds` to Yarn install

packages/build-tools/src/steps/functions/checkout.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts
https://github.com/expo/eas-build/blob/1c3f2019ad05de2c1fc3dda666cc0dcafdd3e492/packages/build-tools/src/customBuildContext.ts#L52
We set the `defaultWorkingDirectory` in our external build context provider as the output of the `getReactNativeProjectDirectory()` function. This function will return `path.join(workingDir, 'build') + relativePathToEasJsonInYourGitRepo`. But unfortunately, if the user didn't call `checkout` this `relativePathToEasJsonInYourGitRepo` might not exist.
Use a boolean value to monitor whether the project was checked out. If it was use the previous defaultWorkingDirectory. If not use project target dir (`workingDir + '/build'`) which always exists and it is the dir when all of the operations should be performed.
=> [ENG-10477][steps][build-tools] use correct default working directory if project wasn't checked out

packages/steps/src/BuildConfig.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts
If you had config like
```yml
build:
name: Demo
steps:
- eas/checkout
-
```
In CLI you would get 
Make `null` invalid.
=> [steps] make `null` build step invalid in Joi schema

packages/steps/src/BuildWorkflow.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts
https://github.com/expo/eas-build/pull/292#discussion_r1401027194
Always throw the first error when running generic job workflow
Add test
=> [steps] make generic job workflow always throw first error

packages/build-tools/src/steps/functions/checkout.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts
It seems like it broke custom builds. Reverting. Will investigate it afterwards
https://staging.expo.dev/accounts/expo-turtle-system-tests/projects/custom-system-test/builds/4d1be4aa-108f-4062-a6a3-0b6c21ee81d8
=> Revert "[ENG-10477][steps][build-tools] use correct default working directory if project wasn't checked out"

packages/logger/src/index.ts, packages/logger/src/pipe.ts
https://linear.app/expo/issue/ENG-10483/investigate-why-a-pair-of-builds-froze-during-yarn-install
https://linear.app/expo/issue/ENG-10483/investigate-why-a-pair-of-builds-froze-during-yarn-install#comment-7fa0acad
https://github.com/expo/eas-build/pull/297#pullrequestreview-1751696608
Companion of:
- https://github.com/expo/eas-build/pull/297
- https://github.com/expo/eas-build/pull/299
Added an optional callback to the function piping spawn output into the child logger. This callback gets executed whenever the child logger calls the info() function to print new log line. In this case it is needed to refresh a timeout so it gets reset after each line from spawn process
Tested by running builds locally with passed callback to reset timeouts and it worked as expected
1. `logger`
2. …
=> [logger] [ENG-10483] Add callback

packages/turtle-spawn/src/index.ts
https://linear.app/expo/issue/ENG-10483/investigate-why-a-pair-of-builds-froze-during-yarn-install
https://linear.app/expo/issue/ENG-10483/investigate-why-a-pair-of-builds-froze-during-yarn-install#comment-7fa0acad
https://github.com/expo/eas-build/pull/297#pullrequestreview-1751696608
Companion of:
- https://github.com/expo/eas-build/pull/297
- https://github.com/expo/eas-build/pull/298
Added an optional callback to the spawn function. This callback gets passed on to the pipeSpawnOutput function to be executed on each line printed by the logger from the spawn process. In this case it is needed to refresh a timeout so it gets reset after each line from spawn process
TODO: update `@expo/logger` version after release
Tested by running builds locally with passed callback to reset timeouts …
=> [turtle-spawn] [ENG-10483] Add and pass callback

packages/build-tools/package.json, packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/functions/configureEASUpdateIfInstalled.ts, packages/build-tools/src/utils/appConfig.ts, yarn.lock
https://linear.app/expo/issue/ENG-10130/ensure-that-read-app-config-is-evaluated-in-a-way-that-it-loads-the
Currently, if the `.env` file is present in project files in the EAS Build and we have `VAL1` both present in the `.env` file and in project secrets, the value used during the app compilation, by prebuild command, and by the `npx expo config --type public` command will be the one from the `.env` file. However, our internal function to read app config won't see the value from the `.env` file and will use the value from secrets. 
It confuses our users because in the `Read app config` build phase they will see the app config resolved by us using our internal function which doesn't use `.env` files, but in some cases if the same envs are present as both secret and in `.env` file it …
=> [ENG-10130][build-tools] use env vars from `.env` files when resolving app config same way expo CLI does

packages/build-tools/src/common/projectSources.ts, packages/eas-build-job/src/common.ts
Since https://github.com/expo/universe/pull/14139 we don't support uploading projects to S3.
Removed `ArchiveSourceType.S3` and its dependents.
`yarn build` in root passed.
=> Remove support for S3 archive type

.github/workflows/coverage.yml, .github/workflows/release.yml, .github/workflows/test-ios.yml, .github/workflows/test.yml, package.json, packages/build-tools/package.json, packages/create-eas-build-function/package.json, packages/create-eas-build-function/templates/typescript/package.json, packages/downloader/package.json, packages/eas-build-job/package.json, packages/local-build-plugin/package.json, packages/logger/package.json, packages/steps/package.json, packages/steps/src/__tests__/fixtures/my-custom-ts-function/package.json, packages/template-file/package.json, packages/turtle-spawn/package.json, yarn.lock
Node 14 is no longer supported and Node 20 is current active
Drop support for Node 14, test against Node 20
Tests
It should land after https://github.com/expo/eas-cli/pull/2175 so the explicit breaking change to drop Node 14 support in EAS CLI lands first
=> [ENG-10799] drop support for node 14

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/index.ts, packages/build-tools/src/ios/xcodeBuildLogs.ts, packages/build-tools/src/steps/functions/findAndUploadBuildArtifacts.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/build-tools/src/utils/artifacts.ts, packages/eas-build-job/src/artifacts.ts, packages/eas-build-job/src/index.ts, packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/ios.ts
This should make adding generic artifacts easier.
- renamed `ArtifactType` to `ManagedArtifactType` and moved to `eas-build-job`. `ManagedArtifactType`s are artifacts recognized and produced by managed workflow — application archive, "build artifacts" and Xcode logs. `GenericArtifactType`s will have much more possibilities.
- changed `uploadArtifacts` to accept a single object argument instead of a list. _Much_ better.
I tested this with [the generic artifact types changes](https://github.com/expo/eas-build/pull/307). Mostly, those are types changes, so if types are all right, the pull request should be all right.
=> Refactor uploading artifacts

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/ios/credentials/__tests__/keychain.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/manager.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/provisioningProfile.test.ios.ts, packages/build-tools/src/ios/xcodeBuildLogs.ts, packages/build-tools/src/steps/functions/findAndUploadBuildArtifacts.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/build-tools/src/utils/__tests__/hooks.test.ts, packages/build-tools/src/utils/artifacts.ts, packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/ios.ts
We won't "upload artifacts" anymore the way we did. Also, artifacts have types which should live nested inside `artifact` property and that property should live _alongside_ logger.
Renamed functions, changed calls.
Believing in TS.
=> Change `uploadArtifacts` into `uploadArtifact`

packages/build-tools/src/context.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/eas-build-job/src/artifacts.ts
We want to allow users to upload multiple artifacts, possibly of similar meaning (e.g. multiple iOS apps).
Added `GenericArtifactType` alongside `ManagedArtifactType`.
=> Add support for generic artifacts

packages/build-tools/src/__tests__/utils/context.ts, packages/build-tools/src/__tests__/utils/job.ts, packages/build-tools/src/__tests__/utils/logger.ts, packages/build-tools/src/steps/functions/__tests__/uploadArtifact.test.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/eas-build-job/src/artifacts.ts
I mistakenly broke the API by removing those values from `allowedValues` when adding `ManagedArtifactType`.
Brought back those values to `allowedValues`, added mapping.
Added test that ensures both values are accepted. While adding test realized input validation does not work like we expect it to. https://linear.app/expo/issue/ENG-11215/fix-validating-inputs
=> Bring back `build-artifact` and `application-archive` artifact type inputs

packages/build-tools/src/ios/credentials/__tests__/manager.test.ios.ts, packages/build-tools/src/steps/utils/ios/credentials/__tests__/manager.test.ios.ts, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/common.ts
It is used to store location of the project archive metadata file
[ENG-10412](https://linear.app/expo/issue/ENG-10412/ui-to-inspect-the-contents-of-eas-build-archive-for-a-build)
=> [ENG-10412] Add `metadataLocation` to ArchiveSource type

packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/startAndroidEmulator.ts, packages/build-tools/src/utils/retry.ts
We want to provide users with an easy way to start an Android emulator for E2E tests.
It's rather simple, just a couple bash commands. I'm happy by using `detached` I was able to work around the ([previously necessary](https://exponent-internal.slack.com/archives/C05JR16NWAX/p1691606736451939)) `echo 'nohup ...' | at now`.
I've played with it a bunch and even was able to start two emulators at once! The emulators are alive as long as `eas-build-worker` is alive, which I think is ok.
=> Add `eas/start_android_emulator` build function

packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/startIosSimulator.ts
Part of the Maestro example.
Moved my tested EAS workflow into a TS function.
It prints all available simulator in the beginning so the users have a list to compare their request to, if they need to. We'll need to make sure to educate people that Simulator Devices, UDIDs are image-specific.
A better version of this function could accept an iOS version to test on, would download and install necessary runtime and create a dedicated device for tests, but I suspect this is enough for now.
I tested it a bunch, with Simulator stopped, started, with different inputs (valid, invalid).
One thing I don't like is that stdout and stderr of a `spawn` can lose ordering, see:
Is there anything we can do about it? Maybe I'm doing something wrong?
=> Create `eas/start_ios_simulator` build function

packages/build-tools/src/builders/custom.ts, packages/build-tools/src/common/easBuildInternal.ts, packages/build-tools/src/common/setup.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/getCredentialsForBuildTriggeredByGitHubIntegration.ts
https://linear.app/expo/issue/ENG-9499/add-support-for-gh-builds
Apply the logic that is used to make GH builds work for standard build flow (resolving envs from `eas.json` and resolving credentials using `eas build:internal`) : 
https://github.com/expo/eas-build/blob/25c65873f3a737ad7afda5db3081f2455a34edb2/packages/build-tools/src/common/setup.ts#L37-L44
https://github.com/expo/eas-build/blob/25c65873f3a737ad7afda5db3081f2455a34edb2/packages/build-tools/src/common/setup.ts#L62-L72
to the custom builds flow.
Read `env` from `eas.json` automatically after preparing project sources:
https://github.com/expo/eas-build/blob/25c65873f3a737ad7afda5db3081f2455a34edb2/packages/build-tools/src/builders/custom.ts#L15-L23
The `eas build:internal` command (to get the credentials) expects the …
=> [ENG-9499][build-tools] add support for custom GH builds with credentials

packages/steps/src/BuildStep.ts, packages/steps/src/scripts/runCustomFunction.ts, packages/steps/src/utils/customFunction.ts, packages/steps/src/utils/shell/spawn.ts
Executing `maestro test` in a custom TS function with `stdin: ignore` seems to be more reliable than with `stdin: pipe`.
Made `spawnAsync` require some `stdio` settings when passing in `logger`. Set `stdin: ignore` when executing shell scripts.
I'm not 1000% sure this may or may not break people's scripts. I don't expect it to though — nobody should depend on `stdin` piped from worker.
I have deployed a worker with this version of `@expo/steps` to staging and it allowed me to run `maestro test` in a script without the `< /dev/null 2>&1 > maestro.log &` hacks. [Staging](https://staging.expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/dbee99a1-cef2-46db-be85-5636a66ae19e) vs [production](https://expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/767c41f9 …
=> Set stdin of shell scripts to "ignore"

packages/build-tools/src/steps/functions/installMaestro.ts
Turns out `fs.mkdtemp('install_maestro')` can [suddenly throw `EACCESS`](https://expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/59f6ccf3-a209-4c7d-b0dd-ab494fb62c04).
Replaced `fs.mkdtemp('string')` with `fs.mkdtemp(path.join(os.tmpdir(), 'string'))`. This is what Node.js documentation suggests to do and also what we do in `www`.
I verified this works right now on both [Android](https://expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/7ca68836-63ef-45bc-8ebf-207c827257e2) and [iOS](https://expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/97f592fa-24b9-4b73-bae4-f88379cf4b65) builds by copying `installMaestro` function into `my-custom-ts-function` and triggering builds manually. Both passed the "Install Maestro" step.
=> Put temporary directories in `os.tmpdir`

packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/functions/configureEASUpdateIfInstalled.ts, packages/build-tools/src/steps/functions/prebuild.ts, packages/build-tools/src/steps/functions/runGradle.ts, packages/eas-build-job/src/context.ts, packages/eas-build-job/src/index.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/__tests__/BuildStepContext-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/__tests__/utils/context.ts, packages/steps/src/cli/cli.ts, packages/steps/src/scripts/runCustomFunction.ts, packages/steps/src/utils/expodash/duplicates.ts, packages/steps/src/utils/expodash/uniq.ts, packages/steps/src/utils/template.ts
We want to let users depend on `staticContext` properties.
Added `BuildStaticContext` type and used it anywhere we reference `staticContext`.
I considered making everything generic with `TStaticContext` to better handle tests, but in the end decided to cast in tests `as unknown as BuildStaticContext`.
This mostly changes types. Automated tests.
=> Add type to `staticContext`

packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/ios.ts
https://linear.app/expo/issue/ENG-11196/create-custom-build-example-slacking-team-members
We want to allow the user to customise their Slack messages in custom builds with build details. One of those should be the link to the build, which we don't want to be build step specific, since the same url will be valid and constant for all build steps. In such a case, the build link has been added as a new field to the Job object, and will be set either by cli or www before the build starts
Added new field to the Job object and to schema validator
Updated automated tests
=> [eas-build-job] [ENG-11196] Add optional buildExpoUrl field to Job

packages/build-tools/src/steps/easFunctionGroups.ts, packages/build-tools/src/steps/functionGroups/maestroTest.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/steps/src/BuildConfigParser.ts, packages/steps/src/BuildFunctionGroup.ts, packages/steps/src/BuildStep.ts, packages/steps/src/utils/template.ts
We want to help developers get started with EAS Build + Maestro.
Added another function group that takes care of setting up environment for Maestro, running the actual tests and uploading test results later.
Ideas for improvement:
- support multiple flows (implemented)
- skip setup of (Maestro, Simulator, Emulator) if a matching # is ready (not implemented)
I ran it on my computer and:
- iOS Simulator could not boot
- Android script could not run:
Maybe tomorrow it will work.
=> Add `eas/maestro_test` function group

packages/build-tools/src/steps/functionGroups/maestroTest.ts
After the app is built, before we test it we need to install it!
Added what already worked in my other tests:
https://github.com/expo/eas-custom-builds-example/blob/e2fbfe2afb37d8d8af9ed465f4a4741ccf5a4d81/.eas/build/development-build-ios.yml#L27-L32
https://github.com/expo/eas-custom-builds-example/blob/e2fbfe2afb37d8d8af9ed465f4a4741ccf5a4d81/.eas/build/development-build-android.yml#L24-L30
Deploy and test.
=> Install apps in `maestro_test`

packages/build-tools/src/steps/functionGroups/maestroTest.ts
https://expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/4e0ed832-ec6d-4e76-8c98-3a38cf60f380
- fixed wrong bash command (do -> then, **$**FILES_FOUND
- fixed Maestro artifact path (`.maestro` -> `.maestro/tests`)
I have verified manually by running those scripts with `bash` that they should work.
=> Fix installing apps in `maestro_test`

packages/build-tools/src/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/utils/expoUpdates.ts
eas-build equivalent of https://github.com/expo/eas-cli/pull/2243.
Run test.
=> [build-tools] Handle expo-updates canary versions

packages/create-eas-build-function/templates/javascript/README.md, packages/create-eas-build-function/templates/javascript/package.json, packages/create-eas-build-function/templates/typescript/README.md, packages/create-eas-build-function/templates/typescript/package.json
Our current readme is outdated and doesn't reference https://docs.expo.dev/custom-builds/functions/ tutorial (which is the best way to start IMO)
Update readme. Make it more "cheerful" and reference our tutorial.
@sjchmiela code review and him verifying that this is actually user friendly 😅
=> [ENG-11467][create-eas-build-function] improve readme in custom build function templates

packages/eas-build-job/src/common.ts
https://exponent-internal.slack.com/archives/CLQ58M23X/p1708680627608489
I believe `''` are valid env vars and we should allow it 🤔
=> [eas-build-job] allow secrets to be empty strings

packages/build-tools/src/steps/functionGroups/build.ts
use `eas/use_npm_token` function in `eas/build` function group
use `eas/use_npm_token` function in `eas/build` function group
=> [build-tools] use `eas/use_npm_token` function in `eas/build` function group

packages/build-tools/src/steps/utils/expoUpdates.ts, packages/build-tools/src/utils/expoUpdates.ts
Add a better warning message during a build if the `channel` is not set correctly, as suggested by brent [here](https://linear.app/expo/issue/ENG-11472/add-annotation-for-misconfigured-eas-update-with-link-to-docs#comment-8d7d6fe5)
In the case that the channel is not set:
- If you have a development client build, don't print any warning, because channels are not relevant. 
- Else print:
> This build has an invalid EAS Update configuration: update.url is set to "${easUpdateUrl}" in app config, but a channel is not specified for the current build profile "${jobProfile}" in eas.json.
>- No channel will be set and EAS Update will be disabled for the build.
>- Run \`eas update:configure\` to set your channel in eas.json. For more details, see …
=> [ENG-11472][build-tools] better expo update error message

packages/build-tools/src/ios/credentials/keychain.ts, packages/build-tools/src/steps/utils/ios/credentials/keychain.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1709063772203869?thread_ts=1709001502.363679&cid=C02123T524U
don't use `turtle-v2` in keychain name
Tests
=> [build-tools] don't use `turtle-v2` in keychain name

packages/steps/src/BuildStepContext.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/utils/template.ts
https://linear.app/expo/issue/ENG-11196/create-custom-build-example-slacking-team-members
Previously you could interpolate string input with string/number/boolean/object values, but you couldn't interpolate object inputs, even if they had string values with interpolation templates. This change adds support for that.
We can use it for example for allowing users to send Slack messages in custom builds using the Slack Block Kit layout with dynamically injected build details.
Made object interpolable, similar to strings. If the interpolated value is a string it is interpolated as before. If it is an object, it's properties are iterated over and interpolated recursively.
Previous tests continue to pass, added another one for the case when an object input is interpolated
=> [steps] [ENG-11196] Add object interpolation support

packages/build-tools/src/steps/utils/expoUpdates.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/build-tools/src/utils/expoUpdatesCli.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
Same as https://github.com/expo/eas-cli/pull/2251 but for build-tools. This issue (using a single version of config plugins to execute updates related logic rather than the version of config plugins the app uses) seems to be pretty widespread.
This PR applies the same strategy: call into the app versioned expo-updates CLI to resolve runtime version (if possible, falling back to single version config plugins for now).
Copy paste code.
1. Follow instructions to do build locally using local copy of eas-cli and eas-build.
2. run `~/expo/run-with-local-eas-build.sh build --local`, see runtime version is consistently resolved.
=> [build-tools] Update expo-updates runtime version resolution

packages/build-tools/src/steps/functions/__tests__/sendSlackMessage.test.ts, packages/build-tools/src/steps/functions/sendSlackMessage.ts
https://linear.app/expo/issue/ENG-11196/create-custom-build-example-slacking-team-members
Added support for object payload of slack messages for usage with the slack block kit
Depends on: https://github.com/expo/eas-build/pull/350
Added a second input for the message contents - `payload`. It is mutually exclusive with `message` input, so providing both will result in an error, but one of them is required so providing none will also result in an error.
`payload` is a JSON type input and contains the Slack message in their Block Kit layout form.
With the recent changes in the `steps` package it is also possible to interpolate values in these message blocks for richer messages with build details
Automatic tests pass
Tested manually
Config
Message
=> [build-tools] [ENG-11196] Support object input for Block Kit messages

packages/build-tools/src/steps/functions/configureEASUpdateIfInstalled.ts, packages/build-tools/src/steps/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/steps/utils/expoUpdates.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/build-tools/src/utils/expoUpdatesCli.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
This reverts commit https://github.com/expo/eas-build/commit/39e063ac5cb25db8809d86110067b3608911f3f3.
Then, this applies a fix on top of it to support older SDKs.
Revert, re-test with SDK 45-50.
```
yarn create expo-app kjdasjkds555hjkdashjk50 --template blank@50
eas init
eas update:configure
~/expo/run-with-local-eas-build.sh build --local
```
(the last step uses a local eas-cli to patch the revert in that repo: https://github.com/expo/eas-cli/pull/2265)
=> Revert "Revert "[build-tools] Update expo-updates runtime version resolution (#354)" (#355)"

packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/ios.ts
Companion to https://github.com/expo/eas-cli/pull/2271
We need this information so we know whether to use the `--auto-submit` flag in Turtle worker when running `eas build:internal`. This information should be provided by WWW.
Add `githubTriggerOptions` to the job object
Tests
=> [ENG-11416][eas-build-job] add github build trigger options to job object

packages/build-tools/src/common/easBuildInternal.ts
Companion to https://github.com/expo/eas-build/pull/357
Use `githubTriggerOptions` data to run the `eas build:internal --auto-submit` command when needed.
Use `githubTriggerOptions` data to run the `eas build:internal --auto-submit` command when needed.
TBA
=> [ENG-11416][build-tools] run `eas build:internal --auto-submit` based on github trigger options data

packages/build-tools/src/steps/functions/__tests__/sendSlackMessage.test.ts, packages/build-tools/src/steps/functions/sendSlackMessage.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/__tests__/BuildStepInput-test.ts
https://github.com/expo/eas-cli/issues/2261
New line characters for messages dynamically generated in previous steps were incorrectly escaped, which resulted in incorrect formatting of the message received over Slack
Added a function that fixes incorrect escape characters when getting values from all inputs
Automated tests pass
Added more tests to cover multiline input as well as incorrectly escaped multiline input based on manual tests
Tested manually
|Config|
|-|
|![Screenshot 2024-03-08 at 13 23 17](https://github.com/expo/eas-build/assets/2974455/1ae37db8-11a2-4bd1-b0fe-e65c0a4bcc83)|
|Before|After|
|-|-|
|<img width="1026" alt="Screenshot 2024-03-08 at 13 22 45" src="https://github.com/expo/eas-build/assets/2974455/fafa04a8-83db-4288-9710-4233f7e6599f">|<img width="1026" …
=> [steps] [Issue 2261] Fix multiline text messages

packages/build-tools/src/steps/functions/checkout.ts, packages/steps/src/BuildStepContext.ts
Don't error the build if `eas/checkout` is called multiple times. Just skip "checkout" if it was already done.
Check if `eas/checkout` was already called. If it was, don't error the build, but skip running it again.
Tests, run test builds
=> [build-tools] don't error the build if `eas/checkout` is called multiple times

packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functionGroups/build.ts, packages/build-tools/src/steps/functions/getCredentialsForBuildTriggeredByGitHubIntegration.ts, packages/build-tools/src/steps/functions/resolveBuildConfig.ts
GitHub build job data is missing a lot of properties, because we don't provide them when we create the build, because we can't, because the config may need to be resolved dynamically, with external dependencies etc.
For this reason `eas build:internal` exists which we call during the build, once all dependencies are installed. We set this up in `get_credentials_for_build_triggered_by_github_integration`. This covered half of the use cases. Turns out we need to call this also in builds that don't need credentials so they have `buildType`, `version` and other properties.
Added `eas/resolve_build_config` function that will be called in _all_ `eas/build` flows. If the build has been triggered by a GitHub trigger, it will call `eas build:internal` to resolve necessary properties, update build …
=> Add `eas/resolve_build_config` function

packages/build-tools/src/common/setup.ts
https://github.com/expo/eas-cli/issues/2267
"This seems to be an issue with the nx-generator so maybe this issue can be closed, but it seems that the build agent output for the Read package.json step should respect that the pre-install hook changed the file which it currently does not seem to do."
Read `package.json` during `Read package.json` step
=> [build-tools] respect modifications made by pre install hook when reading `package.json`

packages/build-tools/src/__mocks__/fs.ts, packages/build-tools/src/__mocks__/fs/promises.ts, packages/build-tools/src/builders/__tests__/custom.test.ts, packages/build-tools/src/builders/custom.ts, packages/build-tools/src/steps/functions/__tests__/findAndUploadBuildArtifacts.test.ts, packages/build-tools/src/steps/functions/findAndUploadBuildArtifacts.ts
They're good to have to debug things. https://exponent-internal.slack.com/archives/C04GPRQCEBG/p1709836166859129
Added fail-safe uploading Xcode logs behind the scenes to custom builds. Also refactored `findAndUploadArtifacts` a bit. One notable change is changing `cwd` for uploading build artifacts from `projectTargetDirectory` to `workingDirectory`. This is what `applicationArchivePath` uses. Which one should it be? Why?
Added some tests.
=> [build-tools] Upload Xcode logs for custom builds behind the scenes

packages/build-tools/src/android/gradle.ts, packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/ios/fastlane.ts, packages/build-tools/src/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/eas-build-job/src/logs.ts
Generic projects (including those that do continuous native generation, CNG) are having some issues with fingerprint when built on EAS build. This is because EAS build does mutations of the native files just before build, thus generating a different logical runtime from the fingerprint perspective. (https://github.com/expo/eas-build/blob/main/packages/build-tools/src/android/expoUpdates.ts#L55 for example). https://github.com/expo/expo/pull/27576 was one possible solution, but this PR (in combination with a eas-build PR) is the better solution.
- Is there a precedent for passing data between build phases?
This PR (in combination with https://github.com/expo/expo/pull/27597) calculates the fingerprint runtime version ahead of project mutation so that a consistent fingerprint is calculated …
=> [expo-updates] Move runtime version calculation ahead of project mutations

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functionGroups/build.ts, packages/build-tools/src/steps/functions/calculateEASUpdateRuntimeVersion.ts, packages/build-tools/src/steps/functions/configureEASUpdateIfInstalled.ts, packages/build-tools/src/steps/functions/runFastlane.ts, packages/build-tools/src/steps/functions/runGradle.ts, packages/build-tools/src/steps/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/steps/utils/android/gradle.ts, packages/build-tools/src/steps/utils/expoUpdates.ts, packages/build-tools/src/steps/utils/ios/fastlane.ts, packages/build-tools/src/utils/expoUpdates.ts
Custom builds equivalent of https://github.com/expo/eas-build/pull/361
Create a new function `eas/calculate_eas_update_runtime_version`. Use the output of this function as an input to `eas/configure_eas_update`, `eas/run_gradle`, and `eas/run_fastlane` functions.
Apply changes to `eas/build`.
Refactor `eas/configure_eas_update` to do the same as its equivalent in the standard build process.
Tests, run builds locally
=> [build-tools] custom builds equivalent of move runtime version calculation ahead of mutations

packages/build-tools/src/steps/functions/useNpmToken.ts
https://discord.com/channels/695411232856997968/1219896632225697834
Fixed path to `npmrc`.
I `cd`ed into the directory where the file is "require"d and verified path with `cat` with an additional `../` does read the file.
=> Fix missing `npmrc` template

packages/steps/package.json, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildConfig-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/utils/__tests__/jsepEval-test.ts, packages/steps/src/utils/jsepEval.ts, packages/steps/src/utils/template.ts, yarn.lock
https://exponent-internal.slack.com/archives/C04GPRQCEBG/p1711393879642069?thread_ts=1711392256.213759&cid=C04GPRQCEBG
ENG-10698
I looked briefly at existing libraries for parsing JS expressions and this seemed small and powerful enough. `jsep` parses the expression and then we use our own, slightly changed and typed copy of [`jsep-eval`](https://github.com/Sensative/jsep-eval/blob/master/src/jsep-eval.js).
I scrapped this quickly together and it looks quite backwards compatible.
I don't plan to do a full release with docs of this yet -- I'm thinking of just having enough to solve the aforementioned use case.
Added tests.
=> Allow dynamic expressions in `if` conditions

packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts
I thought `this.env` contains all env variables, I was wrong.
Renamed `this.env` to `this.stepEnvOverrides` so it's clear it doesn't contain all the env variables. Added `this.effectiveEnv`. Used in `ifCondition`.
Adjusted test.
=> Use all `env` for `ifCondition`

packages/build-tools/src/builders/__tests__/custom.test.ts, packages/build-tools/src/builders/custom.ts, packages/build-tools/src/builders/index.ts, packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/generic.ts, packages/build-tools/src/index.ts, packages/build-tools/src/utils/__tests__/hooks.test.ts, packages/build-tools/src/utils/hooks.ts
We'll use it to trigger generic jobs. For a second I thought we could reuse `runCustomBuildAsync`, but then I figured maybe it's better to have something separate.
Also, wraps preparing project with a build phase. We don't have this in custom build. I think it makes sense to track the time of archive / Git repository download? Or maybe not?
Copied `runCustomBuildAsync`, removed a bunch of things. Reverted changes to `runCustomBuildAsync` done recently.
This adds something new, so should be ok.
=> Export `runGenericJobAsync`

packages/build-tools/src/steps/functions/configureEASUpdateIfInstalled.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/build-tools/src/utils/getExpoUpdatesPackageVersionIfInstalledAsync.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
The runtime version resolution step I added in https://github.com/expo/eas-build/pull/361 is producing null on EAS build even though it's working on a local build. I'm having trouble setting up turtle-v2 and eas-build combination, so instead I'm opting to just add more debug logs to the builder so hopefully I can figure out what's goin on upon the next deploy.
Add `logger.debug` calls.
This is tougher to test since it looks like prod turtle uses `LOGGER_LEVEL` env to determine the log level (which I'm not sure how to override yet for a single build), whilst local uses `EAS_LOCAL_BUILD_LOGGER_LEVEL`. Tested with local anyways:
```EAS_LOCAL_BUILD_LOGGER_LEVEL=debug ~/expo/run-with-local-eas-build.sh build --local```
=> [build-tools] Add more debug logging to EAS Update steps

packages/eas-build-job/package.json, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/generic.ts, packages/eas-build-job/src/ios.ts
We currently set the logger level globally per `worker` service, so we never see debug logs in staging/production because the level there is just `info`. It might be helpful to allow setting logger level on a per-build basis.
I want to allow people to use it like `eas build ... --logger-level debug`
https://exponent-internal.slack.com/archives/C02123T524U/p1711730641664359
@wschurman highlighted a need for something like this
Add `loggerLevel` to the job object
Tests
=> [eas-build-job] allow to set build logger level in job object

packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/build.ts, packages/local-build-plugin/src/config.ts, packages/local-build-plugin/src/exit.ts, packages/local-build-plugin/src/ios.ts, packages/local-build-plugin/src/logger.ts, packages/local-build-plugin/src/types.ts, packages/local-build-plugin/src/workingdir.ts
We want to respect `job.loggerLevel` for local builds as well
Use `job.loggerLevel` for logger level
Tests
=> [local-build-plugin] handle `job.loggerLevel` for local builds

packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
Follow-up to https://github.com/expo/eas-build/pull/374 that tweaks debug logging a bit more.
Now that I have debug logging enabled in staging for my test project, I can see that it is calling the CLI. But for some reason the result is still null for expo-updates runtime version resolution here.
I also added a test post-install hook just to be sure:
```
"eas-build-post-install": "npx expo-updates runtimeversion:resolve --platform android --debug"
```
and that looks fine (fingerprints), so it's very puzzling why this is failing to resolve.
Always print output of command to debug logger.
Inspect.
=> [build-tools] Improve debuggability of command output in updates runtime version resolution

packages/build-tools/src/builders/custom.ts
https://discord.com/channels/695411232856997968/1227710666954248213/1227710666954248213
we used the incorrect dir to load the eas.json
Use correct dir
based on https://github.com/expo/eas-build/blob/a6c4aeb1190b2efab22c59d13052f0e686aea505/packages/build-tools/src/context.ts#L290
tests, test on staging later on
=> [build-tools] use correct dir to read `eas.json` from for custom builds

packages/build-tools/src/utils/expoUpdatesCli.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
As suggested by @sjchmiela on slack, one possible reason we're seeing a discrepancy between prod and local is the presence of the `stdio: 'pipe'` option to `spawnAsync`.
Update call.
Run locally using same process as https://github.com/expo/eas-build/pull/374 test plan, ensure it still works.
=> [build-tools] Use @expo/turtle-spawn instead of @expo/spawn-async and specify stdio and cwd

packages/build-tools/src/utils/expoUpdatesCli.ts
Same as https://github.com/expo/eas-cli/pull/2324 but for the build-tools.
Inspect.
=> [build-tools] Show errors from expo-updates CLI commands more cleanly

packages/build-tools/src/common/setup.ts
https://linear.app/expo/issue/ENG-12057/fail-with-a-nice-and-meaningful-error-message-if-iosbundleidentifier
Fail with a meaningful error message if `ios.bundleIdentifier` or `android.package` is not set for GitHub builds
=> [ENG-12057][build-tools] fail with meaningful error message if `ios.bundleIdentifier` or `android.package` is not set for GitHub builds

.github/workflows/license.yml
https://github.com/expo/eas-build/actions/workflows/license.yml failed and I want to allow us to easily run it again
add workflow_dispatch
dispatch the workflow after it lands
=> [ci] add `workflow_dispatch` as licence workflow trigger as well

packages/build-tools/src/utils/expoUpdates.ts
Now that we know roughly the version of expo-updates that this is supported in, we can hardcode it like we do with others. Need to do this with eas-cli as well.
Closes ENG-12103.
Hardcode.
Inspect.
=> [build-tools] Fill in min expo-updates version for expo-updates CLI

packages/build-tools/package.json
`resources` directory is missing in the _real_ package which causes EAS Preview Updates job to fail. https://expoio.sentry.io/issues/3586517651/?environment=staging&project=1837720&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=0
Added `resources` to `files` in `package.json`.
Ran `npm pack` and confirmed `resources` was added to the tarball.
=> [build-tools] Add `resources` to `build-tools` package

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/steps/functions/calculateEASUpdateRuntimeVersion.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/build-tools/src/utils/expoUpdatesCli.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1714578839191219
pass env vars to expo updates cli
tests
=> [build-tools] pass env vars to expo updates CLI

packages/build-tools/resources/__eas/update-publish.yml
`eas` is not a globally known command in the workflow.
Consulted @szdziedzic, looked at https://github.com/expo/eas-build/blob/e15bbd61ccd025b2846d480e0cf454db962b934d/packages/build-tools/src/common/easBuildInternal.ts#L116, added `npx -y` and `eas-cli` instead of `eas`.
Also added `@latest`.
Also renamed to `__eas/update-publish.yml`. https://github.com/expo/universe/pull/15197
Confirmed it works on my machine.
=> Add `npx -y` to `eas-cli` call

packages/build-tools/src/android/__tests__/expoUpdates.test.ts, packages/build-tools/src/android/expoUpdates.ts, packages/build-tools/src/ios/__tests__/expoUpdates.test.ts, packages/build-tools/src/ios/expoUpdates.ts, packages/build-tools/src/steps/functions/configureEASUpdateIfInstalled.ts, packages/build-tools/src/steps/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/steps/utils/expoUpdates.ts, packages/build-tools/src/utils/__tests__/expoUpdates.test.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/ios.ts, packages/eas-build-job/src/metadata.ts
`eas-build` counterpart to github.com/expo/eas-cli/pull/2357. Classic updates is no longer supported in any SDK version, so this code can be removed.
Closes ENG-12141.
Remove code.
`yarn tsc`
=> [build-tools][build-job] Remove classic updates concepts

packages/build-tools/resources/__eas/update-publish.yml
We need to expose the `robotAccessToken` if we want to use it.
Used `command` interpolation. From what I could see we don't interpolate values in `env`. I checked that when interpolating, undefined falls back to `''`, so this should not break development (where we won't have `robotAccessToken` and instead rely on already authenticated `eas-cli`).
Will test on staging.
=> [build-tools] Add EXPO_TOKEN to eas-cli call

packages/build-tools/src/common/projectSources.ts, packages/eas-build-job/src/common.ts
We want project directories to not only contain information of current commit, but also branch or a tag. We need this for `eas-cli update --auto`.
Previously, we were fetching and checking out a `gitRef` which theoretically could be a commit hash, branch name or a tag, but from looking at `www` it is always a commit hash (which I think is good).
From now on, a Git project archive config will contain:
- `gitCommitHash` — THE commit to fetch and checkout
- `gitRef` — an optional spec like `refs/heads/main`, `refs/tags/v1.0` (or `main` even). We will parse this ref and, when fetching, set a destination for the commit via a [refspec](https://www.atlassian.com/git/tutorials/refs-and-the-reflog#refspecs), similarly to [how GitHub does it](https://github.com/actions/checkout/blob/44c2b7a8a4ea60a9 …
=> [build-tools] Set up a branch or a tag when cloning repository

packages/build-tools/src/common/projectSources.ts, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/common.ts
Some cleanup after the migration period.
Made both `gitRef` and `gitCommitHash` required (as in non-optional). `gitCommitHash` is expected to always be provided, `gitRef` can be `null` (if we're building not from a branch or a tag, but from a detached commit). We are not going to use the `gitRef = null` case in `www` yet.
I built this package and linked to `www` in https://github.com/expo/universe/pull/15254. The changes required to make `tsc` ok seemed forward-compatible.
=> Require both `gitCommitHash` and `gitRef`

packages/build-tools/src/utils/expoUpdatesCli.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
don't pass logger to `expo-updates` CLI
don't pass logger to `expo-updates` CLI so we don't produce noisy logs
before: 
after:
=> [build-tools] don't pass logger to `expo-updates` CLI

packages/build-tools/package.json, packages/build-tools/resources/__eas/repack.yml, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/repack.ts, packages/build-tools/src/utils/artifacts.ts, tsconfig.json, yarn.lock
Repack onboarding builds
Add new `eas/__download_and_repack_golden_development_client_archive` custom build function to use `@expo/repack-app` to do the repack + resign
Create a new repo from scratch using the onboarding flow
Add this build profile to your `eas.json`
```json
"repack": {
"developmentClient": true,
"distribution": "internal",
"channel": "development",
"android": {
"image": "latest"
},
"ios": {
"image": "latest",
"config": "repack.yml"
}
},
```
Add `.eas/build/repack.yml`
```yml
build:
name: Demo
steps:
- eas/checkout
- eas/install_node_modules
- eas/__download_and_repack_golden_development_client_archive:
id: download_and_repack_golden_development_client_archive
- eas/upload_artifact:
name: Upload build artifact
inputs:
type: application-archive
path: ${ …
```
=> [build-tools] add new `eas` custom build function for app repacking

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/context.ts, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/common.ts
Follow up to discussion in https://github.com/expo/universe/pull/15382
Move repack overrides to Turtle and add `BuildMode.REPACK`
Move repack overrides to Turtle and add `BuildMode.REPACK`
tests
=> [eas-build-job][build-tools] move repack overrides to Turtle and add `BuildMode.REPACK`

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/ios/pod.ts
https://linear.app/expo/issue/ENG-11415/add-timeouts-for-the-install-pods-build-phase
Added a warn and kill timeout for install pods phase, similar to what has been done for install dependencies phase here - https://github.com/expo/eas-build/pull/297
=> [build-tools] [ENG-11415] Add timeout for install pods

packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functionGroups/build.ts, packages/build-tools/src/steps/functions/calculateEASUpdateRuntimeVersion.ts
https://exponent-internal.slack.com/archives/C04PTQN8UTY/p1717496873513409
Default values for build step inputs are provided at the beginning of the build process. At this point in time not all of the `job` data is updated for GH triggered build. It happens in https://github.com/expo/eas-build/blob/d70f544b51913e923803724b9581d830d641186e/packages/build-tools/src/steps/functions/resolveBuildConfig.ts#L33-L42 step. That causes the default value for `workflow` to be invalid.
Make inputs non-required but if the input is not provided fall back to `job` values when executing the step (then `job` values should be correct at this point in time)
Add validation
Tests
=> [build-tools] resolve default values for `eas/calculate_eas_update_runtime_version` function just when executing it

packages/local-build-plugin/package.json, packages/local-build-plugin/src/artifacts.ts, yarn.lock
It seems like the `export default` statement was deleted in `tar` 7.x
We imported `tar` like `import tar from 'tar'` and it seems to be the root cause of the https://github.com/expo/eas-cli/issues/2430 issue (`Cannot read properties of undefined (reading 'c')` - we use tar like `tar.c(...)`)
Uninstall not needed `@types/tar` package and import the `tar` correctly
Test manually
=> [local-build-plugin] import `tar` correctly

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/index.ts, packages/eas-build-job/src/metadata.ts
Update metadata to include fingerprint sources type.
Add fingerprint sources to metadata. Extracted from https://github.com/expo/eas-build/pull/407
=> [eas-build-job] [ENG-12593] add fingerprint sources to metadata

packages/build-tools/src/android/gradle.ts, packages/build-tools/src/steps/utils/android/gradle.ts
Using always `bash` or `sh` seems undesired and it looks like it caused some issues for one of our users https://exponent-internal.slack.com/archives/C02123T524U/p1718651239155819
Use `gradlew` as just `./gradlew` instead of `bash -c sh gradlew`.
The `bash -c sh gradlew` hack was introduced to fix permission issues when executing the file. To preserve the fix I added the `chmod +x` before.
tests
=> [build-tools] fix issues with `./gradlew` being executed with inncorrect shell

packages/build-tools/src/steps/functions/repack.ts
https://exponent-internal.slack.com/archives/CLQ58M23X/p1719753567896349?thread_ts=1716632008.211259&cid=CLQ58M23X
Pass `keyPassword` only if it is defined to avoid passing `pass:undefined`.
tests
=> [build-tools] pass `keyPassword` to `@expo/repack` only if it is defined

packages/build-tools/src/context.ts, packages/build-tools/src/utils/__tests__/hooks.test.ts
Adds support for monorepos to EAS Update GitHub integration.
Used the environment variable passed from `www` to change `workingDirectory`
Tested with microfoam fork. (Don't mind failure to upload assets.)
=> [build-tools] Use `__EXPO_RELATIVE_BASE_DIRECTORY` to update default working directory for generic jobs

packages/build-tools/package.json, packages/build-tools/src/utils/artifacts.ts, yarn.lock
https://linear.app/expo/issue/ENG-12644/reported-archive-size-for-simulator-builds-is-incorrect
calculate artifact size correctly for directory artifacts
Test manually
=> [ENG-12644][build-tools] calculate artifact size correctly for directories

packages/create-eas-build-function/templates/javascript/package.json, packages/create-eas-build-function/templates/typescript/package.json
Noticed that when creating a new build function with `create-eas-build-function`, the "build" script in the new function's `package.json` will not work unless `@vercel/ncc` is added to the package.
Added the missing dependency to both templates.
- CI should pass
- Create a new function, go into the function directory, and call "yarn" and "yarn build". After this change, those steps should work.
=> [create-eas-build-function] Add missing ncc dependency

packages/build-tools/src/steps/functions/installNodeModules.ts, packages/build-tools/src/steps/functions/prebuild.ts
https://github.com/expo/eas-cli/issues/2401#issuecomment-2242242004
It seems like we are running `resolvePackageManager` in the wrong directory for custom builds (`stepsCtx.global.projectTargetDirectory` vs `stepsCtx.workingDir`).
For standard builds, we run `resolvePackageManager` in the `ctx.getReactNativeProjectDirectory()` directory
https://github.com/expo/eas-build/blob/b89f2dc256e611efe5627adfdae94e805cb392e3/packages/build-tools/src/context.ts#L160-L162
that is the default `stepsCtx.workingDir` for custom builds.
Run  `resolvePackageManager` in `stepsCtx.workingDir`
Tests
=> [build-tools] run `resolvePackageManager` function in correct directory for custom builds

packages/eas-build-job/src/metadata.ts
User should be able to choose environment variables set that will be used during build process.
Added `environment` to build `metadata`.
Tested manually with similar changes to `eas-cli`
=> Add `environment` to Metadata

packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts
We don't have full knowledge about the project when triggering the GH build in WWW, because we don't clone the repository there + install node modules. We only do this during the build process itself. We use the `eas build:internal` command to obtain an updated job object. The old job object is overridden with a new one, but it seems that overriding `expoBuildUrl` with `undefined` which is set server-side in WWW is not desired.
Do not override `expoBuildUrl`.
Tests
=> [build-tools] do not override the `job.expoBuildUrl` after resolving job object using `eas build:internal` for GitHub triggered builds

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
When uploading fingerprint, we need to know whether it is a debug fingerprint output or a regular fingerprint output so that when we store it we can always overwrite regular with debug when associated with a runtime version (so we always store the most information).
When the user goes to compare, our comparison function will allow comparing debug to non-debug and inform the user when this is the case.
Also store whether the fingerprint is a debug fingerprint.
tsc, run test
=> [eas-build-job] Add field to fingerprint metadata indicating whether it is a debug fingerprint

packages/steps/src/BuildWorkflow.ts
https://linear.app/expo/issue/ENG-13151/commented-out-lines-in-message-template-fail-the-send-slack-message
The function `step.shouldExecuteStep(hasAnyPreviousStepFailed)` was throwing an error which was not caught by the `try/catch` wrapping the actual step execution which resulted in a failed build without logs
Wrapped the function determining if the step should be executed in a try/catch block. The caught error is logged, as is a message that the runner failed to evaluate if the step should be executed or not, so the user knows what's going on. The step is then skipped and the build is failed
Automated tests pass
Manual testing
Before, when interpolated step didn't exist
Now, when interpolated step don't exist
Now, when interpolated step exists
=> [eas-build] [steps] [ENG-13151] Catch errors while evaluating if step should be executed

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts
https://exponent-internal.slack.com/archives/C9PRD479V/p1725286240399969
Make sure that even if save cache phase fails we still upload artifacts
Move save cache phase to be run after the upload app archive
Tests/system tests
=> [build-tools] call upload app archive before saving cache

packages/eas-build-job/src/index.ts, packages/eas-build-job/src/submission-config.ts
I want to be able to expose full submission config from `eas-cli` as expected by `submission-worker`. To keep them in sync I think we may want to use this dependency-shared-everywhere.
Copied submission config schema from `turtle-common` to `eas-build-job`. Renamed a couple of things, flattened structure a bit.
I've used this locally to ensure `eas-cli` responds with what `submission-worker` expects.
=> [eas-build-job] Add submission full config schemas to share between Turtle and EAS CLI

packages/build-tools/package.json, packages/build-tools/src/generic.ts, packages/eas-build-job/src/generic.ts, packages/steps/src/BuildStep.ts, packages/steps/src/BuildTemporaryFiles.ts, packages/steps/src/__tests__/AbstractConfigParser-test.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildFunction-test.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildTemporaryFiles-test.ts, packages/steps/src/__tests__/StepsConfigParser-test.ts, packages/steps/src/index.ts, packages/steps/src/scripts/__tests__/runCustomFunction-test.ts, yarn.lock
Exposing `BuildWorkflow` from `runGenericJobAsync` lets us fetch individual steps and their outputs after the job is complete.
- wraps `buildWorkflow.executeAsync()` with `asyncResult` and returns the result from `runGenericJobAsync` alongside `buildWorkflow`,
- adds `outputs` to `Generic.Job` so the user has a way of telling us which steps outputs are to be considered jobs outputs,
- when a generic job finishes, Worker sends a `robotAccessToken`-authenticated request to [a new `www` endpoint](https://github.com/expo/universe/pull/16916/files).
Also changes the way we're handling `outputsDir` and `envsDir` — we want the outputs and environment variables to be collected always, not only if the step succeeded. And exposes `jsepEval` so we can use it in Worker.
Moreover, removes `outputs` …
=> [eas-build] Expose generic job's `BuildWorkflow`

packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepContext.ts, packages/steps/src/BuildWorkflow.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildWorkflow-test.ts
Moving `hasAnyPreviousStepFailed` from being passed to `shouldExecuteStep` to global context so we can expose `success()` and `failure()` in places other than just the `if` condition.
Added a private property to `BuildStepGlobalContext` with public getter and `markAsFailed`.
Adjusted tests.
=> [steps] Move `hasAnyPreviousStepFailed` to `BuildStepGlobalContext`

packages/build-tools/src/utils/expoUpdates.ts
When there's a runtime version mismatch, the build takes the runtime version calculated at build time. But there's a decent chance the runtime version entity will be for the one calculated locally. This has the effect of making updates behave in an undefined manner since it'd have an invalid deployment, and any updates published locally wouldn't reach the build.
The fix is to throw here instead of warn since it breaks our product.
1. Create canary project
2. Convert app.json to app.config.js
3. Change the line: `"version": process.env.EAS_BUILD ? "1.0.0" : "2.0.0",`
4. `~/expo/run-with-local-eas-build.sh build --local`
See output:
```
...
[CONFIGURE_EXPO_UPDATES]
Runtime version mismatch:
- Runtime version calculated on local machine: 2.0.0
- Runtime version calculated on EAS: 1.0.0
This …
```
=> [build-tools] Fail build upon runtime version mismatch

packages/eas-build-job/src/android.ts, packages/eas-build-job/src/generic.ts, packages/eas-build-job/src/ios.ts
We want the new orchestrator to not need to know about initiating user ID or app ID.
https://github.com/expo/workflow-orchestration/blob/a035d7ea5fa0af1bbdaeca86e862ef99e6a54c4d/internal/watcher/watcher.go#L395-L400
After this is merged, going to upgrade and add them in `www` and `turtle-v2`.
Once this is done, going to make them required and remove the properties from `turtle-v2`.
=> [eas-build-job] Add `appId` and `initiatingUserId` to all job schemas

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/common/eagerBundle.ts, packages/build-tools/src/common/prebuild.ts, packages/build-tools/src/utils/__tests__/project.test.ts, packages/build-tools/src/utils/project.ts, packages/eas-build-job/src/logs.ts
https://linear.app/expo/issue/ENG-13945/add-exportembed-eager
Add a new `EAGER_BUNDLE` build phase which is only run for SDK 52+. In the build phase invoke the `npx expo export:embed --eager --platform platform` command to bundle the JS code eagerly.
Run it for both managed and generic workflow (with native directories or without them).
Test locally:
> [!NOTE]
> The way we display the new build phase on the website will change and use the display name of the new build phase once we update `@expo/eas-build-job` there.
=> [ENG-13945][eas-build-job][build-tools] add new EAGER_BUNDLE build phase for SDK 52+

packages/build-tools/src/common/easBuildInternal.ts
Right now `eas-cli` is not returning `initiatingUserId` or `appId` because we haven't finished https://github.com/expo/eas-cli/pull/2652.
Actually, this is good, because we don't need to rely on `eas-cli` on the topic of `initiatingUserId` or `appId`. Whatever `www` has set on the original job should stand even after build config resolution.
Retained `appId` and `initiatingUserId` on the `sanitizeJob` call.
Turtle should deploy with this change.
=> [build-tools] Do not let `eas-cli` override `initiatingUserId` or `appId`

packages/build-tools/src/steps/functions/eagerBundle.ts, packages/eas-build-job/src/logs.ts
https://exponent-internal.slack.com/archives/C1QMZELP2/p1730225866032479?thread_ts=1730225422.471449&cid=C1QMZELP2
Make the `EAGER_BUNDLE` step display name `Bundle JavaScript`
=> [eas-build-job] make EAGER_BUNDLE step display name "Bundle JavaScript"

packages/eas-build-job/src/__tests__/metadata.test.ts, packages/eas-build-job/src/metadata.ts
In order to support [soft fingerprinting](https://www.notion.so/expo/Soft-fingerprinting-116e5b5735248071951cddcab32ae43d), we need to take a fingerprint on each build. This PR introduces the fingerprintHash field to build metadata to support this feature.
=> [eas-build-job] add fingerprint hash to metadata

packages/build-tools/src/common/easBuildInternal.ts
I have trouble understanding why GitHub builds on the new Orchestrator fail consistently.
I want to know more about the error than "GraphQL request failed". So, I want to print the second part of the output, the stdout.
I ran a local build with overridden `EXPO_TOKEN=invalid`, and printing both stdout and stderr and got:
=> [build-tools] Log `stdout` if `build:internal` fails

packages/build-tools/src/utils/fingerprint.ts
This PR separates out just the backporting portion of https://app.graphite.dev/github/pr/expo/eas-build/460/updates-Change-fingeprint-diff-to-use-versioned-fingerprint-CLI
> Backport the changes from expo/expo#32486 into this local copy of the fingerprint diff mechanism.
This will help debug current fingerprint inconsistencies better before that PR lands (blocked on canary publishes)
[![copypasta](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/ad1d6316-1e6b-41d1-baa1-4e01688fae82/copypasta.png)](https://app.graphite.dev//settings/meme-library?org=expo) 
`yarn tsc`
=> [updates] Update fingerprint diff algorithm

packages/build-tools/src/common/eagerBundle.ts
This should resolve the issue with `npx expo export:embed --eager` getting stuck
https://exponent-internal.slack.com/archives/C5ERY0TAR/p1730760976830759?thread_ts=1730716531.023659&cid=C5ERY0TAR
Use `--dev false` when doing `npx expo export:embed --eager`
Run command with `--dev false` on repro project and it wasn't stuck.
=> [build-tools] use `--dev false` when doing `npx expo export:embed --eager`

packages/build-tools/src/utils/__tests__/diffFingerprintsAsync.test.ts, packages/build-tools/src/utils/diffFingerprintsAsync.ts, packages/build-tools/src/utils/expoFingerprintCli.ts, packages/build-tools/src/utils/expoUpdates.ts, packages/build-tools/src/utils/resolveRuntimeVersionAsync.ts
This adds a call into new @expo/fingerprint CLI (https://github.com/expo/expo/pull/32541) to do diffing when possible, falling back to the local diff when unavailable.
This was done to avoid needing to backport changes from the versioned package in the future to test changes in build.
Test project with versioned fingerprint CLI:
1. Create beta project
2. `eas update:configure`
3. Change app config to app.config.js and add `"version": process.env.EAS_BUILD ? "1.0.0" : "2.0.0",`
3. Add console.log to CLI resolution to verify local CLI is resolved and used.
4. `~/expo/run-with-local-eas-build.sh build --local  --build-logger-level=debug`, see no log indicating that it fell back to local diff indicating that it is using the local copy in the project to do the diffing. See diff looks correct …
=> [updates] Change fingerprint diff to use versioned fingerprint CLI

packages/build-tools/package.json, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/createSubmissionEntity.ts, packages/build-tools/src/utils/promiseRetryWithCondition.ts, packages/build-tools/src/utils/retryOnDNSFailure.ts, packages/eas-build-job/src/context.ts, packages/steps/src/cli/cli.ts, yarn.lock
We want to create submission entities from job runs.
Added an `eas/create_submission_entity` calling our API.
Tested this manually.
=> [build-tools] Add `eas/create_submission_entity`

packages/build-tools/src/__tests__/context.test.ts, packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts
It seems when build configuration is resolved, `robotAccessToken` gets removed from the job.
Made it so we merge secrets instead of overriding them.
Added test.
=> [build-tools] Do not override secrets with empty values

packages/build-tools/src/steps/functions/startAndroidEmulator.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1731088697933349?thread_ts=1731078961.080939&cid=C02123T524U
It seems like installing the correct system image can fail intermittently 
Retry installing it
System tests
=> [build-tools] retry installing system image in eas/start_android_emulator function

packages/build-tools/src/generic.ts, packages/build-tools/src/utils/__tests__/outputs.test.ts, packages/build-tools/src/utils/outputs.ts, packages/build-tools/src/utils/turtleFetch.ts, packages/eas-build-job/src/logs.ts
https://linear.app/expo/issue/ENG-13708/move-uploading-outputs-to-eas-build-and-public-step
Created outputs upload function based on the one existing in turtle, but accepting the `logger` and `expoApiV2BaseUrl` params.
Calling that function at the end of generic job in a new dedicated `Complete job` step, with the logger for that step.
Added mappings for that new step.
Automated tests mostly based on those from Turtle
1) Merge this PR
2) Release new version of `build-tools` and `eas-build-job`
3) Update `eas-build-job` in `website`, merge and deploy
4) Update `build-tools` and `eas-build-job` in Turtle, merge and deploy
=> [build-tools] [ENG-13708] Upload outputs in public step

.github/dependabot.yml, .github/workflows/coverage.yml, .github/workflows/license.yml, .github/workflows/release.yml, .github/workflows/test-ios.yml, .github/workflows/test.yml
All of the GitHub actions used were out of date. This produced warnings during builds, and may eventually fail.
Example: https://github.com/expo/eas-build/actions/runs/10742071508
```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-node@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/Show less
```
```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v2, actions/setup-node@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
I edited the YAML files.
Run the GitHub actions and confirm …
=> Update dependabot actions to current versions + have dependabot suggest future updates

packages/eas-build-job/src/common.ts
`after` makes a lot of sense, `ref_name`, `ref_type` and `commit_message` will be used for `main`, `branch` and `test commit`.
=> [eas-build-job] Add properties to `WorkflowInterpolationContext`

packages/steps/bin/set-env, packages/steps/src/BuildStep.ts, packages/steps/src/utils/envUtils.ts
https://github.com/expo/eas-cli/issues/2728
When setting an env var to a multiline string and then passing it as the context of a Slack message to the `eas/send_slack_message` function the new-line characters are not correctly handled. The implicit new-lines are removed, while explicit `\n` characters are used as `\` and `n`.
Updated the `set-env` bash script to preserve the implicit new-lines when saving the var value to the file.
Added a util function that fixes the explicit escape characters when reading the raw env value from the file and updating the context.
Manual tests
=> [steps] [ENG-14373] Fix multiline slack messages with env vars

packages/build-tools/src/steps/functionGroups/build.ts
We are making a decision in our system whether to execute the credentials or without the credentials flow for the iOS `eas/build` function group based on the presence of `job.secrets.buildCredentials`. However, at the time of making this discussion (before the build starts), these are always missing for GH builds and are only resolved later.
We should rely on `job.simulator` only instead, which is always correctly set for GH builds https://github.com/expo/universe/blob/9eccb36e30da89e17d1c8b748437da99faebfa7d/server/www/src/data/entities/github/GitHubBuildUtils.ts#L165
Only use `job.simulator` to decide which flow to enter
Test it manually
=> [eas-cli] allow running eas/build function group with credentials for iOS GH builds

packages/build-tools/src/steps/functions/installPods.ts
https://exponent-internal.slack.com/archives/C02123T524U/p1736176457964409
It seems like we indeed forgot to pass the logger to this function. I sync this spawn call to be the same as https://github.com/expo/eas-build/blob/2f806e10cfd0ccf6078475633aa09fca4312e9ba/packages/build-tools/src/ios/pod.ts#L15-L36
System tests - see if logs appear
=> [build-tools] add logger to `pod install` spawn call in `eas/install_pods` custom build function

packages/build-tools/package.json, packages/build-tools/src/__mocks__/fs.ts, packages/build-tools/src/__mocks__/fs/promises.ts, packages/build-tools/src/utils/packageManager.ts, packages/create-eas-build-function/package.json, yarn.lock
fixes https://github.com/expo/eas-cli/issues/2782
- `@expo/package-manager@1.7.0` supports bun text-based lock file. this pr bumps the version
- replace `findWorkspaceRoot -> resolveWorkspaceRoot` because of breaking change from https://github.com/expo/expo/pull/31124
- as new package-manager uses `node:fs` under the hood. it breaks jest tests, we have to replicate the [changes](https://github.com/expo/expo/pull/31690) here 
ci passed
=> [build-tools][create-eas-build-function] bump package-manager version

packages/build-tools/src/utils/__tests__/hooks.test.ts, packages/build-tools/src/utils/hooks.ts
https://exponent-internal.slack.com/archives/C9PRD479V/p1736426668589209
Always run the pre-install hook with `npm run` when `yarn` is detected as a package manager to avoid issues with corepack
=> [build-tools] run pre-install hook with npm when yarn is detected as package manager

packages/steps/src/BuildStepContext.ts, packages/steps/src/__tests__/BuildConfigParser-test.ts, packages/steps/src/__tests__/BuildStepContext-test.ts
With Workflows I expect more and more users will want to execute scripts related less to mobile app, in directories other than that of the mobile app.
Currently, `working_directory` works like this:
- relative paths get resolved from the base directory (mobile app directory) — `working_directory: scripts` if base directory is `apps/mobile` ends up being `/home/expo/build/apps/mobile/scripts`
- absolute paths get resolved from VM root — `working_directory: /usr/local/bin` ends up being `/usr/local/bin`.
This makes it cumbersome to execute scripts in directories other than that of mobile app. Say, a user wants to execute scripts in `/apps/web`. If base directory is `apps/mobile`, they'd need to use `../web`. This makes `working_directory` coupled to base directory set in GitHub repository …
=> [steps] Resolve absolute `working_directory` paths from repository root

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts, packages/build-tools/src/common/eagerBundle.ts, packages/build-tools/src/steps/functionGroups/build.ts, packages/build-tools/src/steps/functions/eagerBundle.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1736460082340769
If `ctx.metadata?.developmentClient` is true, skip running the phase
Tests
=> [build-tools] don't run `EAGER_BUNDLE` build phase for dev client builds

packages/build-tools/src/common/setup.ts
https://exponent-internal.slack.com/archives/C017N0N99RA/p1736458086386249
Add env var which disabled this check if set
=> [build-tools] add env var to skip expo doctor check

packages/eas-build-job/src/__tests__/step.test.ts, packages/eas-build-job/src/step.ts, packages/steps/src/BuildConfig.ts, packages/steps/src/BuildFunction.ts, packages/steps/src/BuildStepInput.ts
Currently, it seems the union fails to accept booleans, because `z.boolean()` is outside of the array literal.
Replaced explicit schema with `z.unknown()`, thus letting the build step input parser validate the params (which afaik can be `json`, so anything `JSON.parse` can output).
After this is merged, going to update `eas-build-job` in `www` and change `with` definition in `WorkflowCustomJob`.
---
I also decided to replace some more "type assumptions" to `unknown`. So far our types were often very optimistic, e.g. that a build step input (the one we get from the user) will only ever be of the right type. I've changed that to `unknown` and more type changes needed to follow. Fortunately, those are only type changes (there is [_one_ code …
=> [steps] Allow all values to `steps.with`

packages/build-tools/src/common/easBuildInternal.ts, packages/build-tools/src/common/setup.ts, packages/build-tools/src/steps/functions/resolveBuildConfig.ts
We resolve incorrect and override `projectRootDirectory` when running `eas build:internal` for GCS builds that use NoVcsClient in EAS CLI as VCS client. Adding `EAS_PROJECT_ROOT` env var should fix it.
Use `EAS_PROJECT_ROOT` env var if `EAS_NO_VCS` is used
Tests
=> [build-tools] resolve correct projectRootDirectory during eas build:internal

packages/eas-build-job/src/step.ts, packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildStep-test.ts
We want to support `if` conditions on individual steps in workflows.
- adjusted expected template literals for `ifCondition`
- adjusted interpolation context used for `ifCondition`
- (_somewhat_ unrelated) added descriptions to `StepZ` Zod schema so we can replace `www` copies with using upstream
Added some tests.
=> [steps] Add better workflow support for if condition

packages/build-tools/src/builders/custom.ts, packages/build-tools/src/generic.ts, packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/generic.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/common.ts, packages/eas-build-job/src/generic.ts, packages/eas-build-job/src/ios.ts
For workflows it'll be much easier to let users define `steps` in the workflow file instead of having to do the custom build config and stuff.
Added ability to pass `steps` in build jobs. Alongside, we need to send `workflowInteprolationContext`, so added that too.
Tested manually by running both manual and GitHub workflow build jobs. Also ran a custom build and a regular build from `eas-cli`.
=> [eas-build-job] Allow `steps` in build jobs

package.json, packages/steps/src/__tests__/BuildStep-test.ts, yarn.lock
I've been having issues with VS Code complaining rules for `@typescript-eslint/no-throw-literal` and `.../ban-types` were missing.
I've decided to try upgrading ESLint config. So far so good.
CI should be green.
=> [chore] Upgrade ESLint

packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildStep-test.ts
https://exponent-internal.slack.com/archives/C06EFBQK3B7/p1737419576613249
Removed warning. Unified logic.
Removed test.
=> [steps] Do not print warning about non-defined outputs in step

packages/build-tools/src/steps/functions/uploadArtifact.ts
In generic jobs the default artifact type has been `application-archive` so far. I want to change it to let ourselves handle generic artifacts differently in `worker`.
Made it so that the default is `GenericArtifactType.OTHER` if the job lacks `platform`. Corresponding PR — https://github.com/expo/turtle-v2/pull/2052.
TS does not complain, tested end-to-end.
=> [build-tools] Make `.other` the default artifact type in generic jobs

packages/steps/bin/set-output, packages/steps/src/BuildStep.ts, packages/steps/src/__tests__/BuildStep-test.ts
I think we've been doing `.trim()` on output values because of plain `echo` in `set-output`.
Added `-n` to `echo`, removed `.trim()`. Then changed to use Base64 encoding as we do for environment variables.
Adjusted test. It was wrong all along! Passing of the rest of existing steps confirms steps work in general, right?
=> [steps] Do not trim step output value

packages/eas-build-job/src/submission-config.ts
[ENG-14634: Add support for `groups` option in `fastlane pilot` call](https://linear.app/expo/issue/ENG-14634/add-support-for-groups-option-in-fastlane-pilot-call)
Allow specifying the `groups` option for `fastlane pilot`. This requires passing the `groups` parameter in the submission config, as Turtle validates submit jobs against this schema.
* Allow passing an optional string array parameter `groups` in iOS submission config.
Tested manually.
=> Add `groups` to iOS submission config

packages/eas-build-job/src/step.ts
A union works better for generating JSON schema later, because Zod is able to infer better what is the expected input.
Instead of preprocessing input, we're going to transform it after parsing.
Tests should pass.
=> [eas-build-job] Switch `preprocess` to `union+transform`

packages/build-tools/src/buildErrors/userErrorHandlers.ts, packages/build-tools/src/common/setup.ts, packages/build-tools/src/steps/utils/expoUpdates.ts
https://linear.app/expo/issue/ENG-14950/update-failure-message-to-account-for-eas-variables-rather-than
Replace EAS Secrets in error messages with EAS environment variables
Tests
=> [ENG-14950][build-tools] replace EAS Secrets with EAS environment variables in error messages

packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/generic.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/android.ts, packages/eas-build-job/src/generic.ts, packages/eas-build-job/src/ios.ts
Allow people to auto-enable corepack for their builds/generic jobs by setting `corepack: true` in `eas.json` 
Add `corepack` to job schema
Tests
=> [eas-build-job] add corepack option to tools section of eas.json

packages/build-tools/src/generic.ts, packages/build-tools/src/utils/__tests__/outputs.test.ts, packages/build-tools/src/utils/outputs.ts
I used `fromJSON` in `outputs` in https://github.com/expo/universe/pull/19328, but had to revert it in https://github.com/expo/universe/pull/19361, because `uploadJobOutputsToWwwAsync` was using custom interpolation context when generating values.
Instead of using custom `{ steps }`, used global context to get static context and `JobInterpolationContext` type to ensure we provide `fromJSON`, `toJSON` and all.
Ran a workflow 
```yaml
jobs:
publish_update:
outputs:
updates_json: ${{ steps.step.outputs.updates_json }}
first_update_group_id: ${{ fromJSON(steps.step.outputs.updates_json || '[]')[0].group }}
steps:
- uses: eas/checkout
- uses: eas/install_node_modules
- id: step
run: |
UPDATES_JSON=$(npx -y eas-cli@latest update --non-interactive --json --auto --branch test)
set-output …
```
=> [build-tools] Improve interpolation context on `job.outputs`

packages/build-tools/src/steps/functions/startAndroidEmulator.ts
Emulator is slow.
Found that it is granted default 2 GB of RAM. Increased it to 8 GB which should be ok in all resource classes.
Ran the command manually in a worker environment.
=> [build-tools] Increase memory granted to Android emulator to 8 GB

packages/build-tools/src/steps/functions/startAndroidEmulator.ts
I've been trying to run newer emulators on EAS and they don't start in 30 seconds.
Increased the time we wait for emulator to start.
CI should pass.
=> [build-tools] Increase time waiting for emulator to start

packages/build-tools/src/steps/functions/startAndroidEmulator.ts
I'm trying to start newer Android emulator images on EAS and they fail to adhere to `-prop qemu.uuid=...` `emulator` option which later fails `getEmulatorSerialId` search.
Instead of relying on `-prop qemu.uuid`, let's use `adb emu avd name`.
```
$ adb emu avd name                    
EasAndroidDevice01
OK
```
=> [build-tools] Replace `-prop qemu.uuid` with AVD name check

packages/build-tools/src/common/installDependencies.ts, packages/build-tools/src/common/prebuild.ts, packages/build-tools/src/common/setup.ts, packages/build-tools/src/steps/functions/installNodeModules.ts, packages/build-tools/src/utils/__tests__/packageManager.test.ts, packages/build-tools/src/utils/packageManager.ts, packages/build-tools/src/utils/project.ts
Takeover of https://github.com/expo/eas-build/pull/463
https://exponent-internal.slack.com/archives/C02123T524U/p1731420965266849?thread_ts=1731420501.834709&cid=C02123T524U
https://exponent-internal.slack.com/archives/C02123T524U/p1731421835879399
We want to move over to using "frozen lockfile" when installing dependencies on EAS.
Use "frozen lockfile" if :
- `EAS_NO_FROZEN_LOCKFILE` environment variable is _not_ present AND
- we know the SDK version is not <= 52 AND
- we know the React Native version is not <= 0.79.
Don't use frozen lockfile after prebuild as prebuild can sometimes modify `the package.json`.
This is technically a breaking change? Which is why I'm making it for SDK53+ (not SDK52+). Can't do anything about the non-SDK projects though… we can do the switch now or never… …
=> [build-tools] Use "`--frozen-lockfile`" for SDK53+

packages/build-tools/jest/setup-tests.ts, packages/build-tools/package.json, packages/build-tools/src/__mocks__/fs.ts, packages/build-tools/src/__mocks__/fs/promises.ts, packages/build-tools/src/ios/credentials/__tests__/distributionCertificate.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/keychain.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/manager.test.ios.ts, packages/build-tools/src/ios/credentials/__tests__/provisioningProfile.test.ios.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/__tests__/downloadBuild.test.ts, packages/build-tools/src/steps/functions/downloadBuild.ts, packages/build-tools/src/steps/utils/ios/credentials/__tests__/distributionCertificate.test.ios.ts, packages/build-tools/src/steps/utils/ios/credentials/__tests__/keychain.test.ios.ts, packages/build-tools/src/steps/utils/ios/credentials/__tests__/manager.test.ios.ts, packages/build-tools/src/steps/utils/ios/credentials/__tests__/provisioningProfile.test.ios.ts, packages/build-tools/src/utils/__tests__/files.test.ts, packages/build-tools/src/utils/artifacts.ts, packages/build-tools/src/utils/files.ts, packages/build-tools/src/utils/strings.ts, yarn.lock
https://exponent-internal.slack.com/archives/C06EFBQK3B7/p1746668839849089 Closes https://github.com/expo/eas-build/pull/512.
Followed Szymon's suggestion from https://github.com/expo/eas-build/pull/512#pullrequestreview-2650487396 and set up downloading builds in TS. Mostly used what we've had in `submission-worker`. Cleaned up the logic a bit and added test.
Added integration-ish tests for the function. Planning to land this, then replace a few builds-downloading scripts in staging with `eas/download_build` and test on staging.
Also tested a bunch locally.
=> [build-tools] Add `eas/download_build`

packages/build-tools/src/steps/functions/downloadBuild.ts
Fixed how we create temp directories. We have a working example here we can follow: https://github.com/expo/eas-build/blob/1ef1754153197e74568677b1761be35d764b82c4/packages/build-tools/src/steps/functions/installMaestro.ts#L133
Once deployed I'll rerun https://staging.expo.dev/accounts/sjchmiela/projects/staging-app/workflows/0196cf0e-512f-7727-81de-e3491a045d10.
=> [build-tools] Fix `mkdtemp` trying to create `/tmpabcdef`

packages/eas-build-job/src/submission-config.ts
https://linear.app/expo/issue/ENG-15743
This PR adds support for the `changelog` field in both iOS and Android submission configurations. This allows users to specify release notes for their app submissions with `eas submit`.
Updated the Zod schema in `submission-config.ts` to include an optional `changelog` field for both iOS and Android.
- tested as part of a larger chunk of pending changes with `eas submit --changelog someValue`
=> [submission-config] add changelog parameter

packages/eas-build-job/src/__tests__/android.test.ts, packages/eas-build-job/src/__tests__/ios.test.ts, packages/eas-build-job/src/common.ts
to reuse `BuildMode.REPACK` for the new workflow repack job.
the new workflow repack acts like a custom build. we should keep its job steps.
test with local turtle repack workflow run
=> [eas-build-job] keep job steps for repack

packages/steps/src/BuildStep.ts, packages/steps/src/BuildStepInput.ts, packages/steps/src/__tests__/BuildStep-test.ts, packages/steps/src/__tests__/BuildStepInput-test.ts, packages/steps/src/scripts/__tests__/runCustomFunction-test.ts, packages/steps/src/scripts/runCustomFunction.ts, packages/steps/src/utils/__tests__/customFunction-test.ts, packages/steps/src/utils/customFunction.ts
Currently, the legacy `${ ... }` interpolation uses env from global context, meaning it won't have access to `env:` provided to the step. That `env:` provided to the step is only accessible in `BuildStep`.
To add support for step `env` interpolation, we're going to need to provide `interpolationContext` from the `BuildStep` to `BuildStepInput` when getting the input value.
At the same time I think using `.value` to get input value is convenient and I don't want to change the API so functions need to `getValue({ interpolationContext })`. Let's let functions keep doing `inputs.app_path.value` and interpolation happen behind the scenes.
In order to do that, I'm changing the type of `inputs` passed to build step functions from `BuildStepInputById = Record<string, BuildStepInput>` to …
=> [steps] Simplify inputs passed to step functions

packages/build-tools/src/common/projectSources.ts, packages/build-tools/src/steps/functions/__tests__/downloadBuild.test.ts, packages/build-tools/src/steps/functions/downloadBuild.ts
https://github.com/expo/universe/pull/20604#issuecomment-2979765403
We should use `robotAccessToken` because `EXPO_TOKEN` may be overridden by the user to an `AccessTokenEntity`.
Instead of using `env.EXPO_TOKEN` we're going to use `robotAccessToken` from secrets.
Tested manually by:
- changing `launcher` to pass some invalid `repositoryUrl` to worker for clone.
- running an `eas/download_build`.
```yaml
on:
push:
branches: ['*']
jobs:
download_build:
steps:
- run: ls -lah
- uses: eas/checkout
- run: ls -lah
- uses: eas/download_build
with:
build_id: 6a3ff454-6a8b-42fc-b540-3e2ed831abbd
```
The URL must have refreshed, because I see directory contents. Downloading build would have succeeded, otherwise I would get `UNAUTHORIZED`, not `GCS_FILE_NOT_FOUND`.
=> [build-tools] Move from `EXPO_TOKEN` to `robotAccessToken`

packages/build-tools/package.json, yarn.lock
repack 0.2.5 added [environment variables support](https://github.com/expo/repack-app/pull/30). that would help to resolve build variants issue using environment variables. 
bump repack 0.2.5
- ci passed
- test local turtle with build variants and pass `EXPO_PUBLIC_TEST` from eas.json
```js
const bundleIdentifier = process.env.EXPO_PUBLIC_TEST === 'test' ? 'dev.expo.kudo.sdk53' : 'dev.expo.kudo.sdk53.develop';
/** @type {import('expo/config').ExpoConfig} */
module.exports = ({ config }) => ({
...config,
ios: {
bundleIdentifier,
}
});
```
=> [build-tools] bump repack 0.2.5

packages/build-tools/src/context.ts, packages/build-tools/src/steps/easFunctions.ts, packages/build-tools/src/steps/functions/downloadArtifact.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts
We want to allow users to download artifacts produced by other jobs in a workflow.
Added an `eas/download_artifact` function. It accepts :
- either `name: string`
- or `artifact_id: string`
input. It proceeds to call `api.expo.dev/v2/workflows/:workflowRunId/download-artifact` added in https://github.com/expo/universe/pull/20837. The route then redirects to a signed download URL.
We may need to add more options in the future (downloading multiple artifacts by name prefix, multiple names, disabling unarchiving and stuff), but for now this should be ok.
Note: This pull request allows downloading by `artifact_id`, but it is currently not possible — `eas/upload_artifact` does **not** output an `artifact_id`. Will do in a separate pull request.
This also changes `eas/upload_artifact` to allow …
=> [build-tools] Add `eas/download_artifact`

packages/build-tools/src/steps/functions/repack.ts
show more information when repack spawnAsync failed.
log stdout and stderr when spawnAsync failed
|before|after|
|-|-|
|
tested repack on sdk 51 project (which doesn't support `npx expo export:embed --bytecode`)
=> [build-tools] add spawnAsync error log

packages/eas-build-job/src/common.ts
Support Cloudflares R2 as an Archive source type
=> [eas-build-job] ArchiveSourceType supports R2

packages/build-tools/src/builders/common.ts
This check prevents the migration of builds to R2 as we no longer need to pass the artifact via the build context
https://github.com/expo/turtle-v2/pull/2282
Internal testing
=> [builder] accept null archive artifact

packages/build-tools/src/steps/functions/internalMaestroTest.ts, packages/build-tools/src/steps/functions/startAndroidEmulator.ts, packages/build-tools/src/utils/AndroidEmulatorUtils.ts, packages/build-tools/src/utils/__integration-tests__/AndroidEmulatorUtils.test.ts, packages/build-tools/src/utils/findMaestroPathsFlowsToExecuteAsync.ts
https://expo.dev/accounts/affirm-inc/projects/mobile/workflows/01988a12-1653-7b3d-a33b-82940ad467cc
We now wait for `.lock` files to be deleted. We also ask `emulator` to kill in 1 second rather than 20.
Integration tests passed.
=> [build-tools] Fixes around Android emulator x Maestro tests

packages/build-tools/src/steps/functions/internalMaestroTest.ts, packages/build-tools/src/utils/AndroidEmulatorUtils.ts
Android emulator lockfiles are still an issue — https://expo.dev/accounts/affirm-inc/projects/mobile/workflows/0198a2d2-0281-7347-a525-6d7cf6065c41#job-0198a2e3-86eb-7b9f-9417-94adf5d432cf.
I _think_ maybe the error is not coming from _our_ code, but from `fs.cp` instead? Let's remove the lockfiles before copying.
Also, let's wait a second after the original device is killed. Then the emulator should get killed.
Also, let's fix the screen recording names and strip the `/home/expo/..../` part from them.
Ran a local test.
=> [build-tools] Android Maestro fixes

packages/build-tools/src/utils/AndroidEmulatorUtils.ts
Cloning emulator still fails with ENOENT on lockfile.
Worked with Claude:
- it found I was removing lockfiles from destination directory before copying the source to destination
- it suggested wrapping removing stuff with `try`-`catch`.
Ran an Android Maestro test locally and it looks like it did clone the Emulator properly.
=> [build-tools] Wrap removing lockfiles with `try`-`catch`

packages/build-tools/src/common/projectSources.ts
Having the ability to look inside project archive when debugging users' problems is helpful.
So far, GitHub and workflow builds did not contain project metadata file because it was only being created in `eas-cli` on `build`.
Context — the way EAS works is:
- a worker starts
- it receives information about the job to run from the orchestrator
- if it is a non-custom build:
- it [prepares project sources](https://github.com/expo/eas-build/blob/15184f0fb293e3b6b4001574bf9eb01c3edf841f/packages/build-tools/src/common/projectSources.ts#L18)
- if it is a custom build or a non-build:
- it prepares project sources inside "project source directory" ([link](https://github.com/expo/eas-build/blob/39473145241909a647ee6643ee5281476c910d5b/packages/build-tools/src/generic.ts#L18))
- most often it has a …
=> [build-tools] Upload project metadata file when missing on builds

packages/build-tools/src/builders/ios.ts
Post R2 migration, we no longer need to pass the artifact via the build context. We already removed this for the common builder https://github.com/expo/eas-build/pull/566
Apply same logic to resign builds
Internal testing
=> [ios-builder] accept null archive artifact

packages/build-tools/src/utils/AndroidEmulatorUtils.ts
I want to investigate emulator performance. Maybe there's a flag that would work better in our CI environment?
Added support for optional `ANDROID_EMULATOR_EXTRA_ARGS` environment variables to be passed to `emulator` spawn.
Land in staging and play with it.
=> [build-tools] Add support for passing `ANDROID_EMULATOR_EXTRA_ARGS`

packages/build-tools/src/utils/AndroidEmulatorUtils.ts
This makes Emulators go brrr and we support hardware acceleration in our nested-virtualization VMs.
Ran [a workflow](https://expo.dev/accounts/sjchmiela/projects/expo-affirm/workflows/01991653-e0b7-7be1-9bd0-4e1dbc736659) with `ANDROID_EMULATOR_EXTRA_ARGS: '-accel on'`. The screen recording feels much faster than the one without `-accel on`. It also succeeded a test that otherwise would have always flake.
Land and observe `maestro_test` success rate not drop. Talk to customers.
=> [build-tools] Enable Android Emulator hardware acceleration

packages/build-tools/src/steps/functions/startAndroidEmulator.ts, packages/build-tools/src/utils/AndroidEmulatorUtils.ts, packages/build-tools/src/utils/__integration-tests__/AndroidEmulatorUtils.test.ts
I and Claude think the problem with performance when using `pixel_X` devices on EAS is increased screen density. I want to play with running `pixel_X` devices, but with lower screen density. Supposedly, going from the default device (640x360@ 160 dpi) to Pixel 4 (2280x1080 @ 440 dpi) may have great performance impact.
Added support for adding extra lines to `config.ini` through `ANDROID_EMULATOR_EXTRA_CONFIG`.
Planning to land this in production and test a bit.
=> [build-tools] Allow customizing emulator with `ANDROID_EMULATOR_EXTRA_CONFIG`

packages/build-tools/package.json, packages/build-tools/src/utils/AndroidEmulatorUtils.ts, yarn.lock
I mistakenly used `getenv` to check "user environment variables". `getenv` uses `process.env` which does not have current environment variables.
Replaced use of `getenv` with a plain `true` / `1` checks.
CI should pass.
=> [build-tools] Do not use `getenv` in `build-tools`

packages/eas-build-job/src/submission-config.ts
https://exponent-internal.slack.com/archives/C011ZMXQ6SZ/p1755530483378679
Related — https://github.com/expo/eas-cli/pull/3031
Changed submission config schema to allow any string as `track`, not only `production`/`internal`/`beta`/`alpha`.
Tested along with all the pull requests in the mix.
=> [eas-build-job] Allow freeform `track` in submission config

packages/build-tools/src/builders/ios.ts, packages/build-tools/src/steps/functions/restoreCache.ts, packages/build-tools/src/steps/functions/saveCache.ts
Provide support for utilizing ccache with the recently added `save` and `restore` cache functions for ios Builds and Workflows. This is intended to reduce job times by relying on our provided cache for redundant work, subsequently leading to efficient jobs and queues.
A cache router has been defined for both builds and workflows. The caching steps are only enabled for builds that run on our workers, denoted with EAS_BUILD_RUNNER. The worker sets relevant environment variables that enables Fastlane to apply ccache https://github.com/expo/turtle-v2/pull/2398
Validated with local build and workflow runs. Observed Fastlane runtime improvement from 3min to ~50 seconds, ensured ccache was successfully restored, used, and saved
Restore step matches key based off package manager diff and checks …
=> [ios-builder] support save and restore ccache for builds and workflows

packages/build-tools/src/context.ts, packages/build-tools/src/customBuildContext.ts, packages/build-tools/src/steps/functions/uploadArtifact.ts, packages/local-build-plugin/src/android.ts, packages/local-build-plugin/src/artifacts.ts, packages/local-build-plugin/src/ios.ts
Users want to download test report of specific jobs in a workflow run.
By exposing `artifact_id`, we let them do:
```yaml
steps:
- uses: eas/download_artifact
with:
artifact_id: ${{ after.maestro_ios.outputs.test_report_artifact_id }}
```
```yaml
jobs:
custom_test:
outputs:
artifact_id: ${{ steps.upload.outputs.artifact_id }}
steps:
- run: echo "hello" > test.txt
- uses: eas/upload_artifact
id: upload
with:
path: test.txt
download_artifact:
needs: [custom_test]
steps:
- uses: eas/download_artifact
id: download
with:
artifact_id: ${{ needs.custom_test.outputs.artifact_id }}
- run: |
echo "Artifact downloaded: ${{ steps.download.outputs.artifact_path }}"
cat "${{ steps.download.outputs.artifact_path }}"
```
=> [build-tools] Expose artifact ID from `eas/upload_artifact`

packages/eas-build-job/src/metadata.ts
Somewhat related to https://github.com/expo/workflow-orchestration/pull/407 and https://github.com/expo/turtle-v2/pull/2405.
We're not using `trackingContext` lately. This makes it so it's optional (it's the only property currently _required_ in metadata).
=> [eas-build-job] Make `Metadata["trackingContext"]` optional

packages/build-tools/src/builders/android.ts, packages/build-tools/src/builders/ios.ts
Support builds for Apps in monorepo's with multiple workspaces. This will now locate the root package manager and use the respective lockfile as the cache key.
generate cache key now leverages packageManager's findPackagerRootDir function instead of assuming root
in root
from a monorepo, nested app
=> [build-tools] locate packager root directory
