packages/local-build-plugin/package.json
yarn.lock

To match https://github.com/expo/turtle-v2/pull/615
🦜 
Same as https://github.com/expo/turtle-v2/pull/615

[local-build-plugin] Bump expo-cli to 4.9.1

---

packages/build-tools/package.json
packages/local-build-plugin/package.json
yarn.lock

latest cli properly handles case where name consists only of unicode character
run android build

update expo-cli and config-plugins

---

packages/build-tools/package.json
packages/local-build-plugin/package.json
yarn.lock

To fix https://github.com/expo/expo-cli/issues/3836

upgrade expo-cli and config-plugins

---

packages/local-build-plugin/package.json
packages/local-build-plugin/src/buildArtifact.ts
yarn.lock

Fixes https://github.com/expo/eas-cli/issues/661
Use dateformat to format datetime.
None

[local-build-plugin] fix date format in artifact filename

---

packages/eas-build-job/src/ios.ts

Add macOS Monterey image

---

DEVELOPMENT.md

docs for publishing local build plugin

[docs] publishing local build plugin

---

packages/eas-build-job/src/errors.ts

Add a user-facing error when the build times out.

[eas-build-job] add build timeout error

---

packages/build-tools/package.json
yarn.lock

https://github.com/expo/eas-cli/issues/1011
I don't have an easy way to reproduce the issue, so I will just test normal build on turtle system tests

[build-tools] fix xcpretty crash

---

packages/build-tools/src/context.ts
packages/build-tools/src/utils/project.ts
packages/local-build-plugin/src/expoCli.ts
packages/turtle-spawn/src/index.ts

when network issues on  macstadium started happening one of the noticeable effects was that `expo doctor` hung for a long time
add max timeout to expo doctor 
report to sentry if it happens

add `expo doctor` back

---

packages/build-tools/src/builders/ios.ts

Previous PR changed how entitlements file are picked from using regexp that matches based on extension to selecting based on pbxproj, but still using first native application target it finds.
This PR ensures that we are using the application target defined in the scheme that is used for this build
Resolve entitlements based on target and buidlConfiguration
Not tested, we are just using util that we already use in eas-cli, so I think it's fine to test turtle directlly

[eas-build] Support entitlements for each application target

---

packages/local-build-plugin/README.md

Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests.
How did you build this feature or fix this bug and why?
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.

chore: correct URL to repo

---

packages/build-tools/src/utils/project.ts

https://linear.app/expo/issue/ENG-4952/skip-expo-doctor-if-project-does-not-use-the-expo-package
Run `expo doctor` only if expo package is installed.
None

[ENG-4952][build-tools] run expo doctor only if expo package is installed

---

packages/eas-build-job/src/ios.ts

Add new iOS builder image for XCode 14
Add new iOS builder image for XCode 14
Tests

[eas-build-job] add new iOS builder image

---

packages/build-tools/src/context.ts
packages/eas-build-job/src/android.ts
packages/eas-build-job/src/ios.ts

Companion to https://github.com/expo/turtle-v2/pull/1057

remove backward compatibility for environment secrets

---

packages/cocoapods-nexus-plugin/lib/cocoapods-nexus-plugin/gem_version.rb
packages/cocoapods-nexus-plugin/lib/cocoapods_plugin.rb

CFSDK pod doesn't work with our proxy correctly
Blacklist CFSDK pod
Tested locally

[cocoapods-nexus-plugin] blacklist CFSDK pod

---

packages/build-tools/src/buildErrors/__tests__/detectError.test.ts
packages/build-tools/src/buildErrors/buildErrorHandlers.ts
packages/build-tools/src/buildErrors/userErrorHandlers.ts

add few custom errors

---

packages/build-tools/src/utils/project.ts
packages/eas-build-job/src/common.ts

[eas-build-job] Add GCS ArchiveSourceType

---

packages/eas-build-job/src/ios.ts

Companion to https://github.com/expo/turtle-v2/pull/1142
Add Xcode 14.1 image

[ENG-6892][eas-build-job] add Xcode 14.1 image

---

packages/eas-build-job/src/__tests__/metadata.test.ts
packages/eas-build-job/src/metadata.ts

[ENG-7161][eas-build-job] add build mode to metadata

---

package.json
packages/build-tools/package.json
packages/downloader/package.json
packages/eas-build-job/package.json
packages/local-build-plugin/package.json
packages/logger/package.json
packages/template-file/package.json
packages/turtle-spawn/package.json
yarn.lock

- Upgrade dependencies
- As per https://github.com/nodejs/release#release-schedule, require node@14 and newer.

Upgrade dependencies + update node version requirements

---

packages/build-tools/src/common/setup.ts

Better error message when expo doctor times out
not tested

[ENG-7455] Add better message on doctor timeout

---

packages/build-tools/src/android/gradle.ts

Normally we set envs like EAS_BUILD_ANDROID_VERSION_CODE at the beginning of a build, so it can be displayed in the initial build phase with other envs. To do that implementation had to be worker code and local-build-plugin, but when building from GitHub that value is not known yet, so we need to set it here.
I considered 2 approaches here:
- (one I selected) Check just before running `./gradlew` if envs are set and if needed pass them to just that command.
- When we run `eas build:internal on EAS Build worker I could override ctx.env object. This would result that all future build phases would see that env.
A simple change and hard to test locally. I will test it on staging.

[build-tools] Fix remote version management for GitHub builds

---

packages/local-build-plugin/src/workingdir.ts

Fix for local build
I forgot to create those directories in the initial PR
Run eas build --local -p android

[local] fix set-env for local builds

---

packages/steps/package.json
packages/steps/src/BuildConfigParser.ts
packages/steps/src/__tests__/BuildConfigParser-test.ts
packages/steps/src/utils/customFunction.ts
yarn.lock

Revert "[ENG-9010][steps] create step to install dependencies and compile custom function modules"

---

packages/eas-build-job/src/android.ts
packages/eas-build-job/src/ios.ts

https://linear.app/expo/issue/ENG-9473/support-setting-pnpm-version-with-easjson

[ENG-9473] Add `pnpm` option to `builderEnvironment`.

---

packages/local-build-plugin/src/logger.ts

Fix logger for custom build when in `--local` mode
Fix logger for custom build when in `--local` mode
Tests

[local-build-plugin] fix local build plugin logger for custom builds

---

packages/build-tools/src/steps/functions/configureAndroidVersion.ts
packages/build-tools/src/steps/functions/configureIosVersion.ts
packages/build-tools/src/steps/utils/android/gradleConfig.ts
packages/build-tools/templates/eas-build-configure-version.gradle.template

Both the app version and version code/build number don't have to exist at the same time.
Handle this case.
Make it work even if only one of these is specified
Tested locally

[build-tools] fix update version functions

---

packages/eas-build-job/src/__tests__/android.test.ts
packages/eas-build-job/src/android.ts
packages/eas-build-job/src/ios.ts

Bun is fast, they hype is real and people want to use it! https://bun.sh/
Mirrored the implementation for `pnpm` version https://github.com/expo/eas-build/pull/254

[ENG-10069] add bun option to eas.json

---

packages/build-tools/package.json
yarn.lock

https://exponent-internal.slack.com/archives/C02123T524U/p1699579569626249
Update `@expo/package-manager`
Run build

[build-tools] update `@expo/package-manager` to `1.1.2`

---

packages/build-tools/package.json
packages/build-tools/src/steps/utils/expoUpdates.ts
packages/build-tools/src/utils/expoUpdates.ts
yarn.lock

https://github.com/expo/eas-cli/issues/2190
Looks legit
Update `@expo/config-plugins` and required imports
Tests

[build-tools] update `@expo/config-plugins` and fix the version required by build tools

---

CODEOWNERS

Add @sjchmiela as code owner
Add @sjchmiela as code owner

[CODEOWNERS] add @sjchmiela as code owner

---

packages/build-tools/src/steps/functions/installMaestro.ts

We need to unmount the installer to be able to remove it and the installer. Otherwise we get the following error — https://staging.expo.dev/accounts/exponent/projects/eas-custom-builds-example/builds/a7584d79-9cd6-47b9-9849-676e61bf18ed.
Added `hdiutil detach` before `fs.remove`
I have verified manually that if I mount the installer and try to remove the enclosing directory it fails. When I `hdiutil detach` first, it succeeds.

Unmount the Java installer before removing in Install Maestro function

---

packages/build-tools/src/steps/functions/installMaestro.ts
packages/build-tools/src/steps/functions/startAndroidEmulator.ts
packages/build-tools/src/steps/functions/startIosSimulator.ts

Szymon explained we should pass `env` wherever we `spawn` for consistency.
Passed `env` wherever I `spawn`ed.
What I want to do is add `~/.maestro/bin` to `PATH` for all worker to see. So I:
- modify the `env` object I get from step context
- modify the global `env` by `global.updateEnv`
- modify the process `env` by updating `process.env.PATH`.
Will test as soon as it lands.

Pass `env` to all recently added `spawn`s

---

.github/workflows/release.yml

Companion to https://github.com/expo/eas-cli/pull/2216
Copied the `turtle-v2` step.
I'll only get to test it when a new version is released.

Open a bumping PR in `eas-cli` too

---

packages/build-tools/src/builders/custom.ts
packages/build-tools/src/generic.ts

https://expo.dev/accounts/szdziedzic/projects/repack-example/builds/79f15a67-2500-47ef-b5ef-549af7af4d83
Add `__eas` hidden functions to custom builds as well

[build-tools] add eas workflow files for custom builds as well

---

packages/build-tools/resources/__eas/repack.yml
packages/build-tools/src/steps/functions/repack.ts

Android repack is broken on prod
Pass keypass in correct format
Create new dir for working dir
test locally

[build-tools] fix Android repack

---

packages/build-tools/src/utils/artifacts.ts

https://exponent-internal.slack.com/archives/C02123T524U/p1717424734493159?thread_ts=1717421226.138899&cid=C02123T524U
Print artifact sizes before uploading to GCS
Print artifact sizes before uploading to GCS
Run build locally

[build-tools] print artifacts sizes

---

packages/create-eas-build-function/templates/javascript/package.json
packages/create-eas-build-function/templates/typescript/package.json

update templates dependencies
update templates dependencies

[create-eas-build-function] update templates dependencies

---

packages/build-tools/package.json
yarn.lock

Companion to https://github.com/expo/eas-cli/pull/2498
bump `@expo/config` and `@expo/config-plugins` version
tests, system tests

[build-tools] bump `@expo/config` and `@expo/config-plugins` version

---

packages/build-tools/src/common/eagerBundle.ts
packages/build-tools/src/steps/easFunctions.ts
packages/build-tools/src/steps/functionGroups/build.ts
packages/build-tools/src/steps/functions/eagerBundle.ts

Follow-up to https://github.com/expo/eas-build/pull/452
Add the `eas/eager_bundle` custom build function and update the `eas/build` function group.
Test locally

[ENG-13945][build-tools] add eas/eager_bundle function and update eas/build function group

---

packages/build-tools/src/builders/android.ts
packages/build-tools/src/builders/ios.ts

https://exponent-internal.slack.com/archives/C1QP38NQ5/p1730320280506949?thread_ts=1730299156.349599&cid=C1QP38NQ5
Add env var to disable new step
Add env var to disable new step

[build-tools] add env var to disable bundle javascript step

---

packages/eas-build-job/src/logs.ts

https://www.notion.so/expo/Workflows-feedback-from-Brent-13de5b57352480e187e4e5c1e0aca9b0?pvs=4#13de5b57352480758907d2655f271624
Changed wording.

[eas-build-job] Change "fail build" to "fail job"

---

packages/steps/src/utils/__tests__/jsepEval-test.ts
packages/steps/src/utils/jsepEval.ts

https://github.com/expo/universe/pull/17465

[steps] Update `jsepEval`

---

packages/build-tools/package.json
yarn.lock

Bump @expo packages versions to include Cedric's Windows fix
Bump @expo packages versions to include Cedric's Windows fix
Bump Expo SDK version to include Cedric's Windows fix

bump @expo/config and @expo/config-plugins versions

---

packages/build-tools/src/steps/functions/startAndroidEmulator.ts
packages/build-tools/src/steps/functions/startIosSimulator.ts

We want to allow sharding Maestro tests. For this, we need to have started multiple devices to run tests on.
Added optional `count` parameter to `start_ios_simulator` and `start_android_emulator`.
Then, if it is greater than `1` we:
- stop the original Simulator/emulator
- clone it to `eas-simulator-${i}` and start.
I tested both platforms.
```
Available Simulator devices:
- iPhone 16 Pro (2474A1C1-1273-4F95-A1CE-148D1F4F4255) on com.apple.CoreSimulator.SimRuntime.iOS-18-2
- iPhone 16 Pro Max (06BF7815-B5D1-4A6D-964F-217F9EA63B85) on com.apple.CoreSimulator.SimRuntime.iOS-18-2
- eas-01 (34E3F29E-5B17-40C3-8AEE-46E97F3EB5E7) on com.apple.CoreSimulator.SimRuntime.iOS-18-2
- eas-simulator-1 (836B3C6D-86BE-4093-A59D-EF58B8FE47BE) on com.apple.CoreSimulator.SimRuntime.iOS-18-2
- iPhone 16 …
```

[eas-build] Support starting multiple Simulators/emulators

---

CODEOWNERS

This is my last day 😢 
Remove myself from CODEOWNERS

remove Szymon from CODEOWNERS
